--  WAREHOUSE - AdelWiggins stocking locations
--  Generated by awdemo/tools/gen-awdemo-data.py - do not edit by hand.
--  Dates are anchored to as-of 2026-09-08; regenerate before a demo.

INSERT INTO WAREHOUSE (WH_CODE, WH_NAME, LOCATION, ACTIVE_FLAG) VALUES
  ('LAX', 'Los Angeles Main Plant', 'Los Angeles, CA - AS9100D machining and assembly', 'Y'),
  ('VAL', 'Valencia Machining Center', 'Valencia, CA - CNC detail parts and finishing', 'Y'),
  ('HUN', 'Huntington Operations', 'Huntington, WV - clamp fabrication and moulding', 'Y'),
  ('MIA', 'Aftermarket Spares Depot', 'Miami, FL - MRO and AOG spares distribution', 'Y'),
  ('ELP', 'Wiggins Mining Distribution', 'El Paso, TX - mining fast-fuel product centre', 'Y');

