--  SUPPLIER - approved suppliers
--  Generated by awdemo/tools/gen-awdemo-data.py - do not edit by hand.
--  Dates are anchored to as-of 2026-09-08; regenerate before a demo.

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, PHONE, EMAIL, ACTIVE_FLAG) VALUES
  ('AWS001', 'Pacific Aerospace Alloys', 'Dana Whitfield', '310-555-0142', 'dwhitfield@pacaeroalloys.com', 'Y'),
  ('AWS002', 'Meridian CRES Products', 'Luis Obregon', '562-555-0188', 'lobregon@meridiancres.com', 'Y'),
  ('AWS003', 'Titan Bar & Billet Co.', 'Priya Raman', '714-555-0113', 'praman@titanbarbillet.com', 'Y'),
  ('AWS004', 'Elastomer Dynamics Inc.', 'Corey Nakamura', '323-555-0177', 'cnakamura@elastomerdyn.com', 'Y'),
  ('AWS005', 'Precision Fastener Group', 'Marta Delgado', '818-555-0126', 'mdelgado@precisionfast.com', 'Y'),
  ('AWS006', 'Coastal Anodizing & Finishing', 'Ray Kowalski', '562-555-0209', 'rkowalski@coastalanodize.com', 'Y'),
  ('AWS007', 'ThermElectric Components LLC', 'Ingrid Sorensen', '626-555-0154', 'isorensen@thermelectric.com', 'Y'),
  ('AWS008', 'Composite Tube Technologies', 'Aaron Petrosian', '949-555-0198', 'apetrosian@comptubetech.com', 'Y'),
  ('AWS009', 'SealTech Polymers', 'Yolanda Briggs', '909-555-0165', 'ybriggs@sealtechpoly.com', 'Y'),
  ('AWS010', 'Western Spring & Wire', 'Devon Ashby', '661-555-0131', 'dashby@westernspringwire.com', 'Y'),
  ('AWS011', 'Aero Label & Marking Co.', 'Suzanne Vogt', '213-555-0172', 'svogt@aerolabelmark.com', 'Y'),
  ('AWS012', 'Summit Packaging Systems', 'Hector Alanis', '310-555-0119', 'halanis@summitpackaging.com', 'Y'),
  ('AWS013', 'Redline Metal Treating', 'Gordon Meeks', '562-555-0244', 'gmeeks@redlinemetaltreat.com', 'N');

