PGM        PARM(&UPDAT)
  DCL        VAR(&P) TYPE(*CHAR) LEN(2) VALUE('94')
  DCL        VAR(&O) TYPE(*CHAR) LEN(2)
  DCL        VAR(&DC) TYPE(*CHAR) LEN(2)
  DCL        VAR(&OWNER) TYPE(*CHAR) LEN(2) VALUE(NO) /* +
               owner     */
  DCL        VAR(&MBR) TYPE(*CHAR) LEN(10) VALUE('CURRENT')
  DCL        VAR(&ECOMM) TYPE(*CHAR) LEN(1) VALUE('I')
  DCL        VAR(&USER) TYPE(*CHAR) LEN(10)
  DCL        VAR(&UPDAT) TYPE(*CHAR) LEN(1)
  DCL        VAR(&EOJ) TYPE(*CHAR) LEN(1)
  DCL        VAR(&IN90) TYPE(*CHAR) LEN(1) VALUE('1')
  DCL        VAR(&IN91) TYPE(*CHAR) LEN(1) VALUE('0')
  DCL        VAR(&NXK01) TYPE(*CHAR) LEN(2)
  DCL        VAR(&NXK02) TYPE(*CHAR) LEN(2)
  DCL        VAR(&NXK03) TYPE(*DEC) LEN(6 0)
  DCL        VAR(&NXK04) TYPE(*CHAR) LEN(7)
  DCL        VAR(&FCCYY) TYPE(*CHAR) LEN(4)
  DCL        VAR(&LVL) TYPE(*CHAR) LEN(10)
  DCLF       FILE(LOVEBOX/OMMGR) RCDFMT(CHOICE)

  ADDLIBLE   LIB(ZCLIB)
  MONMSG     MSGID(CPF2100)
  RTVJOBA    USER(&USER)
  TRANSMIT/RTVCPUVAL P(&O)
  CHGVAR     VAR(&DC) VALUE(&O)
/*SNDMSG     MSG(&USER || ' OMmgrcl') TOUSR(RWL)                  */

  /* Determine level of user */
  CALL       PGM(LOVEBOX/USRRTV) PARM(&USER OHMGRCL &LVL)

  /* PGMR level show user all REQs  */
  IF         COND(&LVL = PGMR) THEN(GOTO CMDLBL(SUPER))
  GOTO SUPER

  RTVOFCCL   O(&O) OWNER(&OWNER)
TOP:
  CALL       PGM(RTVUNN) PARM(&P)
  CHGVAR     VAR(&DC) VALUE(&O)

/* bypass choice screen for all users, show all types per d/c */
  GOTO       CMDLBL(SUPER)

CHOICE:
  SNDRCVF    RCDFMT(CHOICE)
  IF         COND(&IN03 | &IN12) THEN(RETURN)
  IF         COND(&CORH = H) THEN(CHGVAR VAR(&MBR) +
               VALUE(HISTORY))
SUPER:
  CHKOBJ     OBJ(QS36F/ORMSR) OBJTYPE(*FILE) MBR(&MBR)
  MONMSG     MSGID(CPF9815) EXEC(DO)
    SNDMSGDLY  M('The Requisition file does not exist.') D(3)
    GOTO       CMDLBL(CHOICE)
  ENDDO

  /* CHGVAR     VAR(&O) VALUE(&P)    */
/*  OPNQRYF    FILE((QS36F/ORMSR &MBR *ONLY)) OPTION(*ALL) +
                 QRYSLT('((OMCODE ="'||&ECOMM||'") & +
                 (OMDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)                                     */
  OVRDBF     FILE(ORMSR) TOFILE(QS36F/ORMSR) MBR(&MBR)
/*OVRDBF     FILE(ORMSR) TOFILE(QS36F/ORMSR) MBR(&MBR) +
               SHARE(*YES)                                           */
  OVRDBF     FILE(ORMTX) TOFILE(QS36F/ORMTX) MBR(&MBR)
  OVRDBF     FILE(ORMSRL1) TOFILE(QS36F/ORMSRL1) MBR(&MBR)
  OVRDBF     FILE(ORMPOL) TOFILE(QS36F/ORMPOL) MBR(&MBR)
  OVRDBF     FILE(VENDPABLF) TOFILE(QS36F/VENDPABLF)
  OVRDBF     FILE(ORMSRL1) TOFILE(QS36F/ORMSRL1) MBR(&MBR)
  /*.. Override primary Files..*/
  OVRDSPF    FILE(OMMGR) TOFILE(LOVEBOX/OMMGR)
  OVRDBF     FILE(ASSET) TOFILE(QS36F/A.ASETMS)
  OVRDBF     FILE(COADDRES) TOFILE(QS36F/COADDRES) +
               SEQONLY(*NO)
  /* Secondary files necessary for calls to other MGRs          OHMGR */
  OVRDSPF    FILE(VNMGR) TOFILE(LOVEBOX/VNMGR)
  OVRDSPF    FILE(VNDMGR) TOFILE(LOVEBOX/VNDMGR)
  OVRDSPF    FILE(VPMGR) TOFILE(LOVEBOX/VPMGR)
  OVRDSPF    FILE(VYMGR) TOFILE(LOVEBOX/VYMGR)
  OVRDSPF    FILE(OHMGR) TOFILE(LOVEBOX/OHMGR)
  OVRDSPF    FILE(OIMGR) TOFILE(LOVEBOX/OIMGR)
  OVRDSPF    FILE(OIRMGR) TOFILE(LOVEBOX/OIRMGR)
  OVRDSPF    FILE(WHMGR) TOFILE(LOVEBOX/WHMGR)
  OVRDBF     FILE(VENDPABL62) TOFILE(VENDPABL6)
  /*           OVRDSPF    FILE(OAMGR) TOFILE(LOVEBOX/OAMGR)          */
  /*           OVRDBF     FILE(OITMHIST) TOFILE(QS36F/ORITM) +
               MBR(HISTORY)                              */
  /*           OVRDBF     FILE(OHDRHIST) TOFILE(QS36F/ORHDR) +
               MBR(HISTORY)                              */
  /*           OVRDBF     FILE(OACTHIST) TOFILE(QS36F/OACCT) +
               MBR(HISTORY)                              */
  /*           OVRDBF     FILE(ORECHIST) TOFILE(QS36F/ORECT) +
               MBR(HISTORY)                              */
  /*           OVRDBF     FILE(ACCTTEMP) TOFILE(QS36F/OACCT) MBR(&MBR)*/

  IF         COND(&CORH = H) THEN(DO)
    OVRDBF     FILE(OITMHIST) TOFILE(QS36F/ORITM) MBR(CURRENT)
    OVRDBF     FILE(OHDRHIST) TOFILE(QS36F/ORHDR) MBR(CURRENT)
    OVRDBF     FILE(ORECTHIST) TOFILE(QS36F/ORECT) MBR(CURRENT)
    OVRDBF     FILE(ORHTXHIST) TOFILE(QS36F/ORHTX) MBR(CURRENT)
    OVRDBF     FILE(ORITXHIST) TOFILE(QS36F/ORITX) MBR(CURRENT)
  ENDDO
  ELSE       CMD(DO)
    OVRDBF     FILE(OITMHIST) TOFILE(QS36F/ORITM) MBR(HISTORY)
    OVRDBF     FILE(OHDRHIST) TOFILE(QS36F/ORHDR) MBR(HISTORY)
    OVRDBF     FILE(ORECTHIST) TOFILE(QS36F/ORECT) MBR(HISTORY)
    OVRDBF     FILE(ORHTXHIST) TOFILE(QS36F/ORHTX) MBR(HISTORY)
    OVRDBF     FILE(ORITXHIST) TOFILE(QS36F/ORITX) MBR(HISTORY)
  ENDDO
  OVRDBF     FILE(ORITM2) TOFILE(QS36F/ORITM)
  /* SET PO DATA FOR CALL BACK TO PO MANAGER OHMGR                  */
  /*.. ECOM */


/* added 07/18/2012, opnqry function not needed, select done in pgm */
  GOTO       CMDLBL(NOQRY)

  IF         COND(&ECOMM = E) THEN(DO)
    OPNQRYF    FILE((QS36F/ORHDR &MBR *ONLY)) OPTION(*ALL) +
                 QRYSLT('((OHCODE ="E") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
    OPNQRYF    FILE((QS36F/ORHDRL1 &MBR *ONLY)) +
                 OPTION(*ALL) QRYSLT('((OHCODE ="E") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
    CHGVAR     VAR(&UPDAT) VALUE(&ECOMM)
  ENDDO
  /*.. DROP SHIP sort query..*/
  IF         COND(&ECOMM = D) THEN(DO)
    OPNQRYF    FILE((QS36F/ORHDR &MBR *ONLY)) OPTION(*ALL) +
                 QRYSLT('((OHCODE ="D") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
    OPNQRYF    FILE((QS36F/ORHDRL1 &MBR *ONLY)) +
                 OPTION(*ALL) QRYSLT('((OHCODE ="D") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
  ENDDO
  /*.. INVENTORY sort query..*/
  IF         COND(&ECOMM = I) THEN(DO)
    OPNQRYF    FILE((QS36F/ORHDR &MBR *ONLY)) OPTION(*ALL) +
                 QRYSLT('((OHCODE ="I") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
    OPNQRYF    FILE((QS36F/ORHDRL1 &MBR *ONLY)) +
                 OPTION(*ALL) QRYSLT('((OHCODE ="I") & +
                 (OHDC="'||&DC||'"))') KEYFLD(*FILE) +
                 SEQONLY(*NO)
  ENDDO

NOQRY:

  OVRDBF     FILE(ORHDR) TOFILE(QS36F/ORHDR) MBR(&MBR) +
               SHARE(*YES)
  OVRDBF     FILE(ORHDRL1) TOFILE(QS36F/ORHDRL1) +
               MBR(&MBR) SHARE(*YES)
  /* Secondary files necessary for calls to other MGRs          CUMGR */
  OVRDSPF    FILE(CUMGR) TOFILE(LOVEBOX/CUMGR)
  OVRDSPF    FILE(CSMGR) TOFILE(LOVEBOX/CSMGR)
  OVRDSPF    FILE(TCUMGR) TOFILE(LOVEBOX/TCUMGR)
  OVRDSPF    FILE(CCMGR) TOFILE(LOVEBOX/CCMGR)
  OVRDSPF    FILE(CDMGR) TOFILE(LOVEBOX/CDMGR)
  OVRDSPF    FILE(CEMGR) TOFILE(LOVEBOX/CEMGR)
  OVRDSPF    FILE(CAMGR) TOFILE(LOVEBOX/CAMGR)
  OVRDSPF    FILE(CVMGR) TOFILE(LOVEBOX/CVMGR)
  OVRDSPF    FILE(SCMGR) TOFILE(LOVEBOX/SCMGR)
  OVRDBF     FILE(CUSTOMER) TOFILE(QS36F/CUSTOMEP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTOMES) TOFILE(QS36F/CUSTOMES) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTOMEA) TOFILE(QS36F/CUSTOMEA) +
               MBR(DUP || &O)
  OVRDBF     FILE(CUSTSHIP) TOFILE(QS36F/CUSTSHPP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTCALL) TOFILE(QS36F/CUSTCALP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTDISC) TOFILE(QS36F/CUSTDISP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTEDI) TOFILE(QS36F/CUSTEDIP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTADDR) TOFILE(QS36F/CUSTADDP) +
               MBR(CURRENT)
  OVRDBF     FILE(CUSTVISP) TOFILE(QS36F/CUSTVISP) +
               MBR(CURRENT)
  /* overrides necessary for LTMGRCL */
  OVRDBF     FILE(WIPHIST) TOFILE(QS36F/WIPJOBS) MBR(HISTORY)
  CHKOBJ     OBJ(QTEMP/ZDATA3) OBJTYPE(*FILE)
  MONMSG     MSGID(CPF9801) EXEC(CRTPF FILE(QTEMP/ZDATA3) +
               SRCFILE(LOVEBOX/QDDSSRC) MBR(*FILE) +
               OPTION(*NOSRC *NOLIST) MAXMBRS(*NOMAX) +
               SIZE(*NOMAX) WAITRCD(*NOMAX) LVLCHK(*NO))
  OVRDBF     FILE(ZDATA3) TOFILE(QTEMP/ZDATA3) +
               MBR(ZDATA3)


  /* Secondary files necessary for calls to other MGRs          MQMGR */
  CHGJOB     SWS(00000001)
  OVRDSPF    FILE(MIMGR) TOFILE(LOVEBOX/MIMGR)
  OVRDSPF    FILE(MQMGR) TOFILE(LOVEBOX/MQMGR)
  OVRDSPF    FILE(MRMGR) TOFILE(LOVEBOX/MRMGR)
  OVRDSPF    FILE(MSMGR) TOFILE(LOVEBOX/MSMGR)
  OVRDSPF    FILE(MTMGR) TOFILE(LOVEBOX/MTMGR)
  OVRDSPF    FILE(MWMGR) TOFILE(LOVEBOX/MWMGR)
  OVRDSPF    FILE(WBMGR) TOFILE(LOVEBOX/WBMGR)
  OVRDSPF    FILE(MPMGR) TOFILE(LOVEBOX/MPMGR)
  OVRDSPF    FILE(P14MGR) TOFILE(LOVEBOX/P14MGR)
  OVRDSPF    FILE(RMCAL) TOFILE(LOVEBOX/RMCAL)
  OVRDBF     FILE(MASTSPIT) TOFILE(QS36F/MASTSPIP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPEC) TOFILE(QS36F/MASTSPEP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPED) TOFILE(QS36F/MASTSPED) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPEA) TOFILE(QS36F/MASTSPEA) +
               MBR(DUP || &O)
  OVRDBF     FILE(MASTSPEP) TOFILE(QS36F/MASTSPEP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPRS) TOFILE(QS36F/MASTSPRP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPSC) TOFILE(QS36F/MASTSPSP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPTX) TOFILE(QS36F/MASTSPTP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPPR) TOFILE(QS36F/MASTSPPP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPPP) TOFILE(QS36F/MASTSPPP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPWS) TOFILE(QS36F/MASTSPWP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPVS) TOFILE(QS36F/MASTSPVP) +
               MBR(CURRENT)
  OVRDBF     FILE(MASTSPPV) TOFILE(QS36F/MASTSPPV) +
               MBR(CURRENT)
  OVRDBF     FILE(VENDPAMC2) TOFILE(QS36F/VENDPAMC)

  /* Secondary files necessary for ESTIMATOR                    B$MGR */
  /* Need to do this so files don't get locked                        */
  CHKOBJ     OBJ(QTEMP/MASTSPBX) OBJTYPE(*FILE) MBR(O || +
               &USER)
  MONMSG     MSGID(CPF9800) EXEC(CRTPF +
               FILE(QTEMP/MASTSPBX) +
               SRCFILE(LOVEBOX/QDDSSRC) MBR(O || &USER) +
               OPTION(*NOSRC *NOLIST) MAXMBRS(*NOMAX) +
               SIZE(*NOMAX) WAITFILE(*CLS) +
               WAITRCD(*IMMED) LVLCHK(*NO))
  MONMSG     MSGID(CPF9815) EXEC(ADDPFM +
               FILE(QTEMP/MASTSPBX) MBR(O || &USER))
  OVRDBF     FILE(MASTSPBX) TOFILE(QTEMP/MASTSPBX) MBR(O +
               || &USER)
  CHKOBJ     OBJ(QTEMP/MASTSPB$) OBJTYPE(*FILE) MBR(O || +
               &USER)
  MONMSG     MSGID(CPF9800) EXEC(CRTPF +
               FILE(QTEMP/MASTSPB$) +
               SRCFILE(LOVEBOX/QDDSSRC) MBR(O || &USER) +
               OPTION(*NOSRC *NOLIST) MAXMBRS(*NOMAX) +
               SIZE(*NOMAX) WAITFILE(*CLS) +
               WAITRCD(*IMMED) LVLCHK(*NO))
  MONMSG     MSGID(CPF9815) EXEC(ADDPFM +
               FILE(QTEMP/MASTSPB$) MBR(O || &USER))
  OVRDBF     FILE(MASTSPB$) TOFILE(QTEMP/MASTSPB$) MBR(O +
               || &USER)
  OVRDBF     FILE(MASTSPCT) TOFILE(QS36F/MASTSPCT) MBR(M +
               || &O)

  /*         files necessary for                                VQMGR */
  OVRDBF     FILE(VENDPARM2) TOFILE(QS36F/VENDPARM)
  OVRDBF     FILE(VENDPABLF) TOFILE(QS36F/VENDPABLF)
  OVRDSPF    FILE(VPMGR) TOFILE(LOVEBOX/VPMGR)
  OVRDSPF    FILE(VOMGR) TOFILE(LOVEBOX/VOMGR)
  OVRDSPF    FILE(VPTXMGR) TOFILE(LOVEBOX/VPTXMGR)
  OVRDSPF    FILE(VPPCMGR) TOFILE(LOVEBOX/VPPCMGR)
  OVRDSPF    FILE(VPRBMGR) TOFILE(LOVEBOX/VPRBMGR)

 /*         files necessary for for                            VPMGR */
             OVRDSPF    FILE(VPMGR) TOFILE(LOVEBOX/VPMGR)
             OVRDSPF    FILE(VOMGR) TOFILE(LOVEBOX/VOMGR)
             OVRDSPF    FILE(VPPCMGR) TOFILE(LOVEBOX/VPPCMGR)
             OVRDSPF    FILE(VPTXMGR) TOFILE(LOVEBOX/VPTXMGR)
             OVRDSPF    FILE(VPRBMGR) TOFILE(LOVEBOX/VPRBMGR)

  DAOFWKCL   FCCYY(&FCCYY)

/* added 07/18/2012, if super view,  pass blank d/c(&O) to pgm  */
             IF         COND(&LVL = PGMR) THEN(CHGVAR VAR(&O) +
                          VALUE('  '))

  CALL       PGM(LOVEBOX/OMMGR) PARM(&P &O &USER &FCCYY +
               &ECOMM &IN90 &IN91 &EOJ &NXK01 &NXK02 +
               &NXK03 &NXK04)
/*IF         COND(&UPDAT ¬= U) THEN( +
               CLOF       OPNID(ORMSR))                          */
/*CLOF       OPNID(ORHDR)                                           */
/*CLOF       OPNID(ORHDRL1)                                         */
ENDPGM
