#!/bin/sh
# ---------------------------------------------------------------------
#  htdocs assets -> the Profound UI docroot.
#
#  This exists as its own script because it was previously buried inside
#  rebuild-all.sh stage 6b, while the playbook's "full deploy after touching any
#  css/js" recipe ended at deploy-shim.sh. Both were individually correct and the
#  combination was a trap: deploy-shim.sh writes a base64 SNAPSHOT of each
#  template and screen script into every skin's start.html, and verifies that
#  snapshot against local source -- so it passes with flying colours while the
#  standalone files under userdata/ui are still last week's.
#
#  That gap is not theoretical. gt-scan.js was fixed, stamped, rebuilt, shimmed
#  and verified, and the copy the device downloads was still 20891 bytes of
#  August. Anything fetched by URL rather than by snapshot -- gt-zxing.min.js,
#  gt-camtest.html, and every file on the seven skins that carry no shim -- comes
#  from HERE and nowhere else.
#
#  Idempotent. Safe to run alone; deploy-shim.sh runs it first.
# ---------------------------------------------------------------------
set -e
cd "$(dirname "$0")/../.."

DOCROOT=/home/drusso/puidist/htdocs/profoundui/userdata/ui
rc=0

#  gt-version.js is GENERATED, never hand-edited: it is how a stale page finds out
#  it is stale. gt-scan.js pulls it with a cache-buster and, if the stamp here is
#  newer than the copy running, loads the new build and hands over.
#
#  Derived from the display files rather than typed, so it cannot disagree with
#  them -- and it is written before the upload below, so it always ships with the
#  assets it describes.
STAMP=$(grep -ho 'v=[0-9]\{8\}[a-z]' gtwms/qddssrc/gtitmd.json | head -1 | cut -d= -f2)
if [ -z "$STAMP" ]; then echo "cannot read the stamp from gtitmd.json"; exit 1; fi
cat > htdocs/profoundui/userdata/ui/gtcommon/gt-version.js <<EOF
/* GENERATED by gtwms/tools/deploy-assets.sh -- do not edit.
   The current build stamp, fetched by gt-scan.js with a cache-buster so a page
   running an older copy can notice and upgrade itself without a reload. */
window.__gtStamp = '$STAMP';
EOF
echo "gt-version.js -> $STAMP"

echo "assets -> $DOCROOT"
for d in htdocs/profoundui/userdata/ui/gt*; do
  name=$(basename "$d")
  printf '  %-16s ' "$name"
  if ssh dev "mkdir -p '$DOCROOT/$name'" && scp -q "$d"/* "dev:$DOCROOT/$name/"; then
    echo "ok    $(ls "$d" | wc -l) files"
  else
    echo "FAIL"; rc=1
  fi
done

#  Prove the SERVER now serves what is on disk. Comparing local file to local
#  file proves nothing, and a byte-count mismatch is the exact signature of the
#  bug this script was extracted to prevent.
echo "verifying over HTTPS (what the device actually downloads)"
BASE=https://idev.profoundlogic.com:8103/profoundui/userdata/ui
for f in gtcommon/gt-scan.js gtcommon/gt-photo.js gtcommon/gt-zxing.min.js \
         gtcommon/gt-camtest.html; do
  local_bytes=$(stat -c%s "htdocs/profoundui/userdata/ui/$f" 2>/dev/null || echo 0)
  tmp=$(mktemp)
  code=$(curl -sk -o "$tmp" -w '%{http_code}' "$BASE/$f?cb=$$")
  served=$(stat -c%s "$tmp")
  rm -f "$tmp"
  printf '  %-26s HTTP %s  local %6s  served %6s  ' "$(basename "$f")" "$code" "$local_bytes" "$served"
  if [ "$code" = 200 ] && [ "$local_bytes" = "$served" ]; then echo "ok"
  else echo "MISMATCH"; rc=1; fi
done

exit $rc
