-- SMCOP sample data (REVERSE-ENGINEERED)
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (1, 'StoneRiver Workers Comp', 'Sample insurance carrier #1');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (2, 'Sapiens Insurance Corp', 'Sample insurance carrier #2');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (3, 'Midwest Mutual Carrier', 'Sample insurance carrier #3');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (4, 'Heritage National Ins', 'Sample insurance carrier #4');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (5, 'Pinnacle Risk Carrier', 'Sample insurance carrier #5');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (6, 'Buckeye Group Ins', 'Sample insurance carrier #6');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (7, 'Lakeshore Risk Pool', 'Sample insurance carrier #7');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (8, 'Greater Lakes Mutual', 'Sample insurance carrier #8');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (9, 'Tri-State Carrier', 'Sample insurance carrier #9');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (10, 'Capital Carriers', 'Sample insurance carrier #10');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (11, 'Northwoods Mutual', 'Sample insurance carrier #11');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (12, 'Cardinal Insurance Co', 'Sample insurance carrier #12');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (13, 'Crossroads Carrier', 'Sample insurance carrier #13');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (14, 'Liberty Bell Mutual', 'Sample insurance carrier #14');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (15, 'Stonebridge National', 'Sample insurance carrier #15');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (16, 'Iron Mountain Risk', 'Sample insurance carrier #16');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (17, 'Eagle Bend National', 'Sample insurance carrier #17');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (18, 'Maple Leaf Carrier', 'Sample insurance carrier #18');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (19, 'Riverbend National', 'Sample insurance carrier #19');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (20, 'Bluegrass Carrier', 'Sample insurance carrier #20');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (21, 'Cornerstone National', 'Sample insurance carrier #21');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (22, 'Summit National', 'Sample insurance carrier #22');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (23, 'Beacon National Carriers', 'Sample insurance carrier #23');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (24, 'Lighthouse National', 'Sample insurance carrier #24');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (25, 'Anchor National Carrier', 'Sample insurance carrier #25');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (26, 'Cobblestone National', 'Sample insurance carrier #26');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (27, 'Watershed Carrier', 'Sample insurance carrier #27');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (28, 'Sunrise National', 'Sample insurance carrier #28');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (29, 'Falcon National', 'Sample insurance carrier #29');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (30, 'Briarwood Carrier', 'Sample insurance carrier #30');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (31, 'Crescent National', 'Sample insurance carrier #31');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (32, 'Prairie Carrier', 'Sample insurance carrier #32');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (33, 'Rolling Hills Co', 'Sample insurance carrier #33');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (34, 'Riverstone National', 'Sample insurance carrier #34');
INSERT INTO SMCOP ("CO#", CONAME, COTEXT) VALUES (35, 'Cardinal Mutual', 'Sample insurance carrier #35');
