--  AdelWiggins demo dataset - INVENTORY balances by item and stocking location
CREATE OR REPLACE TABLE INVENTORY (
  ITEM_ID                                  CHAR(10),
  WH_CODE                                  CHAR(3),
  QTY_ON_HAND       FOR COLUMN QTY_O00001  DECIMAL(10,2),
  QTY_ON_ORDER      FOR COLUMN QTY_O00002  DECIMAL(10,2),
  REORDER_POINT     FOR COLUMN REORD00001  DECIMAL(10,2),
  LAST_RECEIPT_DATE FOR COLUMN LAST_00001  DATE,
  LAST_ISSUE_DATE   FOR COLUMN LAST_00002  DATE,
  PRIMARY KEY (ITEM_ID, WH_CODE),
  CONSTRAINT INVENTORY_ITEM_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
  CONSTRAINT INVENTORY_WH_FK   FOREIGN KEY (WH_CODE) REFERENCES WAREHOUSE (WH_CODE)
);

LABEL ON COLUMN INVENTORY (
  ITEM_ID           IS 'Item ID',
  WH_CODE           IS 'Warehouse Code',
  QTY_ON_HAND       IS 'Quantity On Hand',
  QTY_ON_ORDER      IS 'Quantity On Order',
  REORDER_POINT     IS 'Reorder Point',
  LAST_RECEIPT_DATE IS 'Last Receipt Date',
  LAST_ISSUE_DATE   IS 'Last Issue Date'
);
