--  AdelWiggins demo dataset - SUPPLIER_ITEM (approved source list)
CREATE OR REPLACE TABLE SUPPLIER_ITEM FOR SYSTEM NAME SUPPL00001 (
  SUPPLIER_ID           FOR COLUMN SUPPL00001 CHAR(6),
  ITEM_ID                                     CHAR(10),
  LEAD_TIME_DAYS        FOR COLUMN LEAD_00001 INTEGER,
  PURCHASE_COST         FOR COLUMN PURCH00001 DECIMAL(10,2),
  PRIMARY_SUPPLIER_FLAG FOR COLUMN PRIMA00001 CHAR(1) DEFAULT 'N',
  PRIMARY KEY (SUPPLIER_ID, ITEM_ID),
  CONSTRAINT SUPPLIER_ITEM_SUPP_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
  CONSTRAINT SUPPLIER_ITEM_ITEM_FK FOREIGN KEY (ITEM_ID)     REFERENCES ITEM (ITEM_ID)
);

LABEL ON COLUMN SUPPLIER_ITEM (
  SUPPLIER_ID           IS 'Supplier ID',
  ITEM_ID               IS 'Item ID',
  LEAD_TIME_DAYS        IS 'Lead Time (Days)',
  PURCHASE_COST         IS 'Purchase Cost',
  PRIMARY_SUPPLIER_FLAG IS 'Primary Supplier (Y/N)'
);
