-- COADDRNAME : short-name view over COADDRES used by the plant drop-downs
CREATE OR REPLACE VIEW COADDRNAME (COAPLT, SHORTNAME, COANAM, COADEL) AS
  SELECT COAPLT, SHORTNAME, COANAM, COADEL
    FROM COADDRES;

LABEL ON TABLE COADDRNAME IS 'Plant Short Names';
