#!/usr/bin/env python3
"""Make the Pratt Rich Display screens self-sufficient for CSS and JavaScript.

Two problems, both because these screens were built for Pratt's own hosting page
and are now running on a different one:

1. "Onload Error: applyPropertyCSS is not defined".  settings.js defines the
   helpers the screens call from onload; Pratt's Genie start.html loads it
   globally, this instance's does not.

2. The screens rendered with no widget styling at all - black background, icon
   ligature names showing as literal text ("searchGo To Record (F1)"), a collapsed
   grid.  That is what Profound UI's own base stylesheet,
   /profoundui/proddata/css/profoundui.css, being absent from the hosting page
   looks like; it was reproduced exactly by removing only that file from a local
   harness running the real runtime.js against a captured screen.

Both are fixed with the mechanism the screens already use.  Profound UI's runtime
honours "external css" / "external css 2" / ... and "external javascript", and it
defers a screen's onload until those files have loaded.  So each screen now names
everything it needs, in cascade order:

    external css    -> profoundui.css        (base widget styling)
    external css 2  -> pratt_profound.css    (Pratt's house overrides, as before)
    external css 3  -> styles.css            (only where .comboInput is used)
    external css N  -> pratt_theme_fix.css   (keeps labels readable in dark mode)

settings.js is NOT referenced through `external javascript` - see the comment on
that line for why doing so suppresses the screen's onload entirely.  Its contents
are inlined into the onload instead.

It also sets a `color` widget property on label and output-field widgets - see the
comment on set_widget_colours for why CSS alone was not enough.

profoundui.css is listed first so Pratt's overrides still win, and referencing it
at its real proddata URL keeps its relative font URLs resolving.  Loading it twice
is harmless if the hosting page does supply it.
"""
import json, sys
sys.path.insert(0, __file__.rsplit('/', 1)[0])
import rdf_edit

PUI_BASE = '/profoundui/proddata/css/profoundui.css'
STYLES = '/profoundui/userdata/css/styles.css'
THEME_FIX = '/profoundui/userdata/css/pratt_theme_fix.css'
SETTINGS = '/profoundui/userdata/custom/settings.js'


def css_list(screen):
    """Pratt's existing external css entries, in their original order."""
    out, key, n = [], 'external css', 2
    while key in screen:
        out.append(screen[key])
        key = 'external css %d' % n
        n += 1
    return out


def set_css_list(screen, files):
    for k in [k for k in list(screen) if k.startswith('external css')]:
        del screen[k]
    for i, f in enumerate(files):
        screen['external css' if i == 0 else 'external css %d' % (i + 1)] = f


# ---------------------------------------------------------------------------
# Label / output-field colour, set as a widget property rather than in CSS.
#
# The stylesheet route (pratt_theme_fix.css) did not take effect in the real
# browser: the search-panel labels stayed white even though the rules were right
# and the file was listed on the screen.  Rather than keep guessing at why -
# whether the Genie wrapper class differs from the one the skin's own CSS
# implies, or the stylesheet is not reaching the page - this sets the colour
# where nothing can outrank it.
#
# Profound UI declares `color` as a `g:"css"` property, so the runtime renders it
# as an INLINE style on the widget.  Inline beats every stylesheet rule, the skin
# included, in both light and dark mode.
#
# Measured first, with tools/render-screen/labelbg.js: all 32 label widgets and
# every outputField sit on a light background (white, near-white, or the
# selected-row blue) in both colour schemes, so a dark colour is safe everywhere.
#
# Widgets that already carry a `color` are left alone - those are Pratt's own
# deliberate choices, including two whites on the blue side panel and one bound
# to a field so the colour is driven by the program.
PRELUDE_START = '/* --- pratt settings prelude: generated by tools/wire_assets.py, do not edit --- */'
PRELUDE_END = '/* --- end pratt settings prelude --- */'
SETTINGS_SRC = '../../htdocs/profoundui/userdata/custom/settings.js'


def build_prelude():
    """Inline settings.js into the screen itself.

    `external javascript` names /profoundui/userdata/custom/settings.js, but that
    file only exists in this repo - it has never been copied to the IBM i, and
    that copy is owned by CoderFlow's approval step, not by us.  The browser goes
    through the task proxy to the IBM i, finds nothing there and 404s, so every
    handler that calls one of these helpers dies with

        Onrowclick Error: applyPropertyCSS is not defined

    The screen JSON itself always arrives, so the helpers are carried in it.  The
    runtime evaluates a screen's `onload` before the user can click anything, so
    defining them there is early enough for onrowclick, onchange and button
    handlers alike.

    Function declarations are rewritten as explicit `window.` assignments: the
    onload body is eval'd, and a bare `function foo(){}` inside a block would not
    reliably reach the global scope.  The whole thing is guarded, so once the
    assets really are deployed the external file wins and this is a no-op.
    """
    import os, re
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), SETTINGS_SRC),
               encoding='utf-8').read()
    src = re.sub(r'^function\s+(\w+)\s*\(', r'window.\1 = function(', src, flags=re.M)
    body = '\n'.join('  ' + line if line.strip() else line for line in src.splitlines())
    return (PRELUDE_START + '\n'
            + "if (typeof window.applyPropertyCSS !== 'function') {\n"
            + body + '\n}\n'
            + PRELUDE_END + '\n')


def add_prelude(screen):
    """Prepend the prelude to this screen's onload, replacing any earlier copy."""
    onload = screen.get('onload', '')
    if PRELUDE_START in onload:
        head, _, rest = onload.partition(PRELUDE_START)
        _, _, tail = rest.partition(PRELUDE_END)
        onload = head + tail.lstrip('\n')
    screen['onload'] = build_prelude() + '\n' + onload.lstrip('\n')


LABEL_COLOUR = '#333333'    # Pratt's own value, from .label in pratt_profound.css
TEXT_COLOUR = '#212121'     # the skin's light-mode value, i.e. what light mode shows


def set_widget_colours(obj):
    changed = 0
    for item in obj.get('items', []):
        cls = item.get('css class')
        if not isinstance(cls, str) or 'color' in item:
            continue
        classes = cls.split()
        if 'label' in classes:
            item['color'] = LABEL_COLOUR
        elif any(c in classes for c in ('outputField', 'outputFieldClear', 'outputFieldOv',
                                        'input', 'search', 'comboInput')):
            # 'input'/'search'/'comboInput' are entry fields.  Their text inherits
            # the same washed out colour, so typed values would be unreadable too;
            # every one of them sits on a light background.
            item['color'] = TEXT_COLOUR
        else:
            continue
        changed += 1
    return changed


def mutate(obj):
    screen = obj['screen']
    set_widget_colours(obj)
    add_prelude(screen)
    files = [PUI_BASE] + [f for f in css_list(screen) if f not in (PUI_BASE, THEME_FIX)]
    if 'comboInput' in json.dumps(obj) and STYLES not in files:
        files.append(STYLES)
    # last, so it also wins on order against anything above it
    files.append(THEME_FIX)
    set_css_list(screen, files)
    # Deliberately NOT setting `external javascript`.  The runtime evaluates a
    # screen's onload inside the callback of the LAST external javascript file it
    # loads - so if that file 404s, the callback never fires and **onload never
    # runs at all**.  settings.js only exists in this repo, never on the IBM i, so
    # naming it here silently killed every screen's onload.  That is why the
    # reported error moved from "Onload Error: applyPropertyCSS is not defined"
    # to "Onrowclick Error: applyPropertyCSS is not defined" - onload had stopped
    # running, so it could no longer even fail.
    #
    # The helpers are carried in the onload prelude instead (see build_prelude).
    # If the assets are ever genuinely deployed to the IBM i, re-adding the
    # property is safe - the prelude is guarded - but it is not needed.
    for k in [k for k in list(screen) if k.startswith('external javascript')]:
        del screen[k]


if __name__ == '__main__':
    for f in ('qddssrc/poselui.dspf', 'qddssrc/pmselui.dspf',
              'qddssrc/podtlui.dspf', 'qddssrc/puisrchui.dspf'):
        changed, total = rdf_edit.rewrite(f, mutate)
        print('%-24s %d of %d screens updated' % (f, changed, total))
