/* GENERATED by gtwms/tools/deploy-assets.sh -- do not edit.
   The current build stamp, fetched by gt-scan.js with a cache-buster so a page
   running an older copy can notice and upgrade itself without a reload. */
window.__gtStamp = '20260811k';
