#!/usr/bin/env python3
"""Generate seed.sql for the Pratt purchasing demo.

Deterministic (fixed seed) so re-running produces the same dataset.  Dates are
anchored on a reference date passed in, defaulting to today, and emitted as
absolute values.  Transaction dates never fall on a weekend.

Usage:  python3 gen_seed.py [YYYY-MM-DD] > seed.sql
"""
import sys, random, datetime as dt
sys.path.insert(0, __file__.rsplit('/', 1)[0])
import catalog as C

random.seed(20261005)
TODAY = dt.date.fromisoformat(sys.argv[1]) if len(sys.argv) > 1 else dt.date.today()
FY = TODAY.strftime('%y')
OUT = []


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def emit(sql):
    OUT.append(sql if sql.lstrip().startswith('--') else sql + ';')


def ins(table, cols, rows):
    if not rows:
        return
    emit('DELETE FROM %s' % table)
    for r in rows:
        vals = ', '.join(q(v) if isinstance(v, str) else str(v) for v in r)
        emit('INSERT INTO %s (%s) VALUES (%s)' % (table, ', '.join(cols), vals))


def workday(d):
    while d.weekday() >= 5:
        d -= dt.timedelta(days=1)
    return d


def biz(days_ago):
    return workday(TODAY - dt.timedelta(days=days_ago))


def cymd(d):
    return int(d.strftime('%Y%m%d')) - 19000000 if d.year >= 1900 else 0


USERS = ['HDAVOLT', 'TMCCUTCH', 'CCRANMER', 'KCHOUIN', 'AIDEMO']
BUYERS = ['HDAVOLT', 'TMCCUTCH', 'CCRANMER']

emit('-- Pratt Industries purchasing demo data')
emit('-- Generated by pratt/data/gen_seed.py - do not hand edit')
emit("-- Reference date: %s" % TODAY.isoformat())

# --------------------------------------------------------------- reference data
ins('COADDRES',
    ['COAPLT','COANAM','SHORTNAME','STREET','STCTST','ORG','LCACCT','PAYOTQ','COAJOB','COAPO#','COADEL'],
    [(p, n, s, st, cts, org, lc, cc, 0, 0, ' ') for p, n, s, st, cts, org, lc, cc in C.PLANTS]
  + [(d, n, s, st, cts, 'PIUS', 9400, '700100', 90000 + i * 100, 0, 'W')
     for i, (d, n, s, pp, st, cts, rg) in enumerate(C.WAREHOUSES)])

ins('LOCGEO', ['L2WH','PRTM','L2REG','L2DEL'],
    [(d, pp, rg, ' ') for d, n, s, pp, st, cts, rg in C.WAREHOUSES])

ins('SAPINCO', ['INCOCDE','INCODES'], C.FREIGHT)

ins('VENDMST', ['VNUMB','VNNAME','VNCODE','VNEMAL'], C.VENDORS)

ins('CUSTOMEP', ['CUNN','CUID','CUNAME','CUDEL'],
    [(nn, cid, nm, ' ') for nn, cid, nm, mkt in C.CUSTOMERS])

ins('CUSTSHPP',
    ['CSNN','CSID','CSLOC','CSNAME','CSADDR','CSCITY','CSST','CSZIP5','CSZIP4',
     'CSCTRY','CSPOCD','CSORAX','CSR01','CSMAXO','CSX01','CSDEL'],
    [(nn, cid, loc, nm, adr, city, st, z5, z4, 'USA', '', ax, wh, 250000, ' ', ' ')
     for nn, cid, loc, nm, adr, city, st, z5, z4, ax, wh in C.SHIPTOS])

ins('ZCCITY', ['ZZIP','ZCITY','ZSTATE','ZPREF','ZMIND'],
    sorted({(str(z5), city, st, 'P', ' ') for nn, cid, loc, nm, adr, city, st, z5, z4, ax, wh in C.SHIPTOS}))

ins('MASTSAZZ', ['QZZKEY','QZZDTA'],
    [('COUNTRYUSA', 'UNITED STATES'), ('COUNTRYCAN', 'CANADA'),
     ('COUNTRYMEX', 'MEXICO'), ('COUNTRYAUS', 'AUSTRALIA')])

uoms = sorted({p[7] for p in C.PARTS})
ins('VENDSAZZ', ['VZZKEY'] + ['VZZ%d' % i for i in range(1, 27)],
    [tuple(['BASEUOFM'] + [(uoms[i] if i < len(uoms) else '') for i in range(26)])])

ins('HELP', ['HLPAPP','HLPSUB','HLPVAL','HLPSEQ','HLPTXT'],
    [(app, sub, 'S%02d' % (i + 1), i + 1, txt if sub == 'SORTT' else col)
     for app, lst in C.SORTS.items()
     for i, (txt, col) in enumerate(lst)
     for sub in ('SORTT', 'SORTV')])

ins('USERIDS', ['UIUSER','UINN','UISAP'],
    [('HDAVOLT','94','SAPHD001'), ('TMCCUTCH','94','SAPTM001'),
     ('CCRANMER','94','SAPCC001'), ('KCHOUIN','94','SAPKC001'),
     ('AIDEMO','94','SAPDEMO01')])

ins('USRLEVEL', ['ULUSER','ULPGM','ULLVL'],
    [(u, p, 'PGMR') for u in USERS for p in ('OHMGR','OMMGR','OIRMGR','*DEFAULT')])

# ------------------------------------------------------------------ vendor parts
vp_rows, vpaco_rows, vpabl_rows, wh_rows, mq_rows = [], [], [], [], []
BREAK_FACTORS = [(1, 1.00), (5, 0.97), (10, 0.94), (25, 0.90), (50, 0.86)]

for (part, vend, maj, mino, sku, desc, desc2, uom, lead, per, cost, pct) in C.PARTS:
    qtys = [b * max(1, per // 10) for b, f in BREAK_FACTORS]
    csts = [round(cost * f, 2) for b, f in BREAK_FACTORS]
    frts = [round(cost * 0.02 * f, 2) for b, f in BREAK_FACTORS]
    adds = [round(c + f, 2) for c, f in zip(csts, frts)]
    row = [part, '94', 0, sku, desc, desc2, maj, mino, per, lead, pct, uom,
           0.0, round(cost, 5), 0, round(cost * 0.015, 2), round(cost * 0.005, 2),
           'USA', biz(400).isoformat(), 0, cymd(biz(30)), 'HDAVOLT', ' ', '']
    row += [uom, '', '', '', '']          # VRUOM1-5
    row += ['']                           # VRFILL2
    row += qtys + csts + [''] + frts + adds
    vp_rows.append(tuple(row))

    for dc in ('CO', 'VA', 'SH', 'WA', 'HE', 'SI'):
        vpabl_rows.append((sku, dc, vend, part, desc, desc2, uom,
                           0.0, 0, round(cost * 0.015, 2), round(cost * 0.005, 2),
                           0, biz(30).isoformat(), ' ', '',
                           desc, desc2, '', '', 'HDAVOLT', '')
                          + tuple(qtys) + tuple(csts) + ('',) + tuple(frts) + tuple(adds))

    mq_rows.append(('94', 0, sku, per, per, 1.0, round(cost, 5), 0, cymd(biz(30)), 'HDAVOLT', 1.0, ''))
    wh_rows.append(('CO', '94', 0, sku, per))

VP_COLS = (['VRPART','VRNN','VRID','VRIT','VQDESC','VRDES2','VRMAJ','VRMIN','VRUNIQ',
            'VRLEAD','VRPCT','VRPER1','VROVHD','VRUPTL','VRCCOD','VRSRCL','VRSRCU',
            'VRORIG','VREFFD','VREXPD','VRCYMD','VRUSER','VRDEL','VRFILL1']
           + ['VRUOM%d' % i for i in range(1, 6)] + ['VRFILL2']
           + ['VRQTY%d' % i for i in range(1, 6)] + ['VRCST%d' % i for i in range(1, 6)]
           + ['VRFILL3'] + ['VRFRT%d' % i for i in range(1, 6)] + ['VRADD%d' % i for i in range(1, 6)])
ins('VENDPART', VP_COLS, vp_rows)

VY_COLS = (['VYSKU','VYDC','VYVEND','VYPART','VYDESC','VYDESC2','VYUOM','VYOVHD','VYCCOD',
            'VYSRCL','VYSRCU','VYEXPD','VYCHGD','VYDEL','VYFIL0']
           + ['VYXT%d' % i for i in range(1, 5)] + ['VYUSER','VYFIL1']
           + ['VYQ%d' % i for i in range(1, 6)] + ['VYC%d' % i for i in range(1, 6)]
           + ['VYFIL2'] + ['VYF%d' % i for i in range(1, 6)] + ['VYA%d' % i for i in range(1, 6)])
ins('VENDPABLF', VY_COLS, vpabl_rows)

ins('MASTSPEP', ['MQNN','MQID','MQIT','MQ#OUT','MQ#PCS','MQMLT','MQCOST','MQCCOD',
                 'MQSYMD','MQUSER','MQUSEX','MQX'], mq_rows)
ins('WAREHOUS', ['WHDC','WHNN','WHID','WHIT','WHORDQ'], wh_rows)

ins('LOCXREF', ['L0LOC','L0LAKT','L0LAK','L0DEL'],
    [(d, 'RTL2', '%-20s' % ('BVP %s' % d), ' ') for d, n, s, pp, st, cts, rg in C.WAREHOUSES])

# Generic (non customer specific) vendor part cost rows, plus one per drop-ship
# customer axis, matching the two CHAIN patterns PODTLUI uses.
VO_COLS = (['VOPART','VOOO','VONN','VOID','VOORAX','VOLOC','VOOVHD','VOCCOD','VOFIL0',
            'VOSRCL','VOSRCU','VOEXPD'] + ['VOQ%d' % i for i in range(1, 6)]
           + ['VOC%d' % i for i in range(1, 6)] + ['VOCYMD','VOUSER','VODEL']
           + ['VOF%d' % i for i in range(1, 6)] + ['VOA%d' % i for i in range(1, 6)] + ['VOX'])
ORGS = sorted({p[5] for p in C.PLANTS})
# VENDPACO's key is (part, org, plant, customer, axis) - it does not include the
# ship-to location, so collapse customers that have more than one location.
SHIPTO_AXES = sorted({(r[0], r[1], r[9], r[2]) for r in C.SHIPTOS}.__iter__(),
                     key=lambda t: (t[0], t[1]))
_seen = set(); _tmp = []
for nn, cid, ax, loc in SHIPTO_AXES:
    if (nn, cid, ax) in _seen: continue
    _seen.add((nn, cid, ax)); _tmp.append((nn, cid, ax, loc))
SHIPTO_AXES = _tmp[:8]
for (part, vend, maj, mino, sku, desc, desc2, uom, lead, per, cost, pct) in C.PARTS:
    qtys = [b * max(1, per // 10) for b, f in BREAK_FACTORS]
    csts = [round(cost * f, 2) for b, f in BREAK_FACTORS]
    frts = [round(cost * 0.02 * f, 2) for b, f in BREAK_FACTORS]
    adds = [round(c + f, 2) for c, f in zip(csts, frts)]
    base = (0.0, 0, '', round(cost * 0.015, 2), round(cost * 0.005, 2), 0)
    for org in ORGS:
        vpaco_rows.append((part, org, '', 0, '', '') + base + tuple(qtys) + tuple(csts)
                          + (cymd(biz(30)), 'HDAVOLT', ' ') + tuple(frts) + tuple(adds) + ('',))
    for nn, cid, ax, loc in SHIPTO_AXES:
        vpaco_rows.append((part, 'PIUS', nn, cid, ax, loc) + base + tuple(qtys) + tuple(csts)
                          + (cymd(biz(30)), 'HDAVOLT', ' ') + tuple(frts) + tuple(adds) + ('',))
ins('VENDPACO', VO_COLS, vpaco_rows)

# ---------------------------------------------------------------- transactions
PARTBY = {p[0]: p for p in C.PARTS}
PLANT_OF_WH = {d: pp for d, n, s, pp, st, cts, rg in C.WAREHOUSES}
WH_ADDR = {d: (n, st, cts) for d, n, s, pp, st, cts, rg in C.WAREHOUSES}
SHIPTO_BY = {(nn, cid, loc): r for r in C.SHIPTOS for nn, cid, loc in [(r[0], r[1], r[2])]}
MILL_WH = ['CO', 'VA', 'SH', 'WA', 'HE', 'SI']

CONSUMABLE = [p[0] for p in C.PARTS if p[2] in ('110','120','150','160','170','190')]
CAPITAL    = [p[0] for p in C.PARTS if p[2] in ('130','140')]
DISPLAY    = [p[0] for p in C.PARTS if p[2] == '180']
FREIGHT_P  = [p[0] for p in C.PARTS if p[2] == '900']

# A PO is raised against one vendor, so lines are drawn from that vendor only.
BY_VENDOR = {}
for p in C.PARTS:
    BY_VENDOR.setdefault(p[1], []).append(p[0])

def vendors_for(pool):
    return sorted({pv for pv in BY_VENDOR if any(x in pool for x in BY_VENDOR[pv])})

# Material group -> requisition type code, so OMCODE always matches the part.
# Target line value by material group, so a PO looks like something a buyer
# would really raise: you do not order ten press felts, and you do not raise a
# purchase order for three square inches of printing plate.
VALUE_BAND = {
    '110': (6000, 40000),   # starch
    '120': (4000, 30000),   # wet end chemicals
    '130': (19000, 45000),  # paper machine clothing
    '140': (18000, 60000),  # corrugator rolls and belts
    '150': (1500, 18000),   # flexo print consumables
    '160': (2000, 25000),   # recycling / baling
    '170': (1500, 14000),   # shipping supplies
    '180': (2000, 20000),   # retail display
    '190': (400, 7000),     # plant MRO and PPE
    '900': (150, 1500),     # freight and services
}

def pick_qty(part, rnd):
    (p, pv, maj, mino, sku, desc, desc2, uom, lead, per, cost, pct) = PARTBY[part]
    lo, hi = VALUE_BAND.get(maj, (1000, 10000))
    target = rnd.uniform(lo, hi)
    if cost <= 0:
        return 1
    qty = target / float(cost)
    if per > 1:                       # order in whole packs
        packs = max(1, int(round(qty / per)))
        qty = packs * per
    else:
        qty = max(1, int(round(qty)))
        for step in (1000, 500, 100, 50, 25, 10, 5):
            if qty >= step * 2:
                qty = int(round(qty / step)) * step
                break
    return qty


def code_for(part):
    maj = PARTBY[part][2]
    if maj == '900':  return 'F'
    if maj == '180':  return 'E'
    return 'I'

# PO archetypes: (code, status, method, how many, age range in days, description)
PO_ARCHETYPES = [
    ('I', ' ', 'Y', 22, (3, 45),   'open inventory PO, partially received'),
    ('I', 'C', 'Y', 18, (60, 240), 'closed, fully received'),
    ('I', ' ', 'Y',  8, (55, 120), 'overdue - past due date, nothing received'),
    ('I', 'H', 'N',  6, (1, 12),   'on hold over the approval limit'),
    ('I', 'X', 'N',  4, (20, 90),  'cancelled'),
    ('D', ' ', 'Y',  9, (5, 40),   'drop ship direct to a customer'),
    ('E', ' ', 'Y',  6, (2, 30),   'e-commerce sourced order'),
    ('I', ' ', 'N',  5, (0, 3),    'entered recently, not yet transmitted'),
    ('I', ' ', 'Y',  4, (1, 10),   'rush - customer pick up'),
    ('I', 'C', 'Y',  6, (120, 330),'capital spares, closed'),
]

oh_rows, oi_rows, ot_rows, oit_rows, ec_rows = [], [], [], [], []
wp_rows, ws_rows, om_rows = [], [], []
po_no = 100
req_no = 500
req_for_po = {}

def make_po(code, stat, meth, age, idx):
    """Build one PO header plus its lines, and the requisition(s) behind it."""
    global po_no, req_no
    po_no += 1
    oh_yy, oh_n = FY, po_no
    created = biz(age)
    buyer = BUYERS[idx % len(BUYERS)]

    if code == 'D':
        st = C.SHIPTOS[idx % len(C.SHIPTOS)]
        nn, cid, loc, nm, adr, city, stt, z5, z4, ax, wh = st
        dc, pp = 'DS', nn
        ship = (nm, adr, city, stt, z5, z4)
    else:
        # Conyers GA is both the head office and the default plant the search
        # screens open on, so it carries roughly half the activity; the rest is
        # spread across the other five mills.
        dc = (random.choice(['CO','CO','CO','CO','VA','SH','WA','HE','SI'])
              if code == 'I' else 'MS')
        pp = PLANT_OF_WH[dc]
        nn, cid, loc = '', 0, ''
        wname, wstreet, wcts = WH_ADDR[dc]
        city, stt = wcts.split(',')[0], wcts.split(',')[1].strip().split()[0]
        z5 = int(wcts.split()[-1].split('-')[0])
        ship = (wname[:30], wstreet, city, stt, z5, 0)

    pool = (DISPLAY if code == 'E' else
            CAPITAL if stat == 'C' and age > 110 else CONSUMABLE)
    cands = vendors_for(pool)
    vend = cands[idx % len(cands)]
    vpool = [x for x in BY_VENDOR[vend] if x in pool]
    nlines = random.choice([1, 1, 2, 2, 3, 4, 5, 6])
    picked = random.sample(vpool, min(nlines, len(vpool)))
    frt = 'CPU' if (stat == ' ' and meth == 'Y' and age <= 10 and idx % 7 == 0) else \
          random.choice(['PPA', 'PPD', 'COL', 'FOB'])

    ordid = 'EC%s%06d' % (FY, po_no) if code == 'E' else ''
    if code == 'E':
        ec_rows.append((ordid, oh_yy, pp, oh_n, 'SO%s-%05d' % (FY, 4000 + idx)))

    changed = workday(min(TODAY, created + dt.timedelta(days=random.randint(0, 12))))
    oh_rows.append((oh_yy, oh_n, pp, dc, stat, code, meth, vend, frt, buyer,
                    created.isoformat(), buyer, changed.isoformat(),
                    '%02d.%02d.%02d' % (random.randint(7, 17), random.randint(0, 59), random.randint(0, 59)),
                    nn, cid, loc, ship[0], 'RECEIVING DEPT', ship[1], ship[2], ship[3], ship[4], ship[5],
                    'USA', '', ordid, 0, '', '', '', 'X'))

    total = 0.0
    for ln, part in enumerate(picked, start=1):
        (p, pv, maj, mino, sku, desc, desc2, uom, lead, per, cost, pct) = PARTBY[part]
        qty = pick_qty(part, random)
        unit = round(cost * random.uniform(0.97, 1.04), 5)
        due = workday(created + dt.timedelta(days=lead))
        if stat == 'C':
            lstat, rq = 'C', qty
        elif stat == 'X':
            lstat, rq = 'X', 0
        elif age > 50 and stat == ' ':
            lstat, rq = ' ', 0                     # overdue, nothing received
        else:
            lstat = ' '
            rq = round(qty * random.choice([0, 0, 0.25, 0.5, 0.75]), 3)
        req_no += 1
        om_req = req_no
        req_for_po[(oh_yy, oh_n, ln)] = om_req
        oi_rows.append((oh_yy, oh_n, pp, ln, p, desc, sku, uom, qty, rq,
                        round(qty - rq, 3), 0, '0001-01-01', unit, due.isoformat(), lstat,
                        om_req, '%-7s' % '', 0, maj + mino, sku[:9], int(maj), '', 0, '', 0, 0,
                        buyer, changed.isoformat(), '08.30.00', 'X'))
        total += qty * unit
        if ln == 1 and random.random() < 0.45:
            oit_rows.append((oh_yy, pp, oh_n, ln, p, '',
                             'CONFIRM LOT NUMBERS ON THE PACKING LIST.', 'DELIVER TO DOCK 4 BETWEEN 07:00 AND 15:00.',
                             '', '', '', '', '', '',
                             'INTERNAL: SOURCED AGAINST REQ %s%06d.' % (FY, om_req), '', '', '', '', '', '', '',
                             buyer, created.isoformat(), ''))

    if frt in ('PPA', 'COL') and random.random() < 0.35:
        fp = PARTBY[FREIGHT_P[0]]
        oi_rows.append((oh_yy, oh_n, pp, len(picked) + 1, fp[0], fp[5], fp[4], 'EA',
                        1, 0, 1, 0, '0001-01-01', round(random.uniform(180, 1450), 5),
                        workday(created + dt.timedelta(days=2)).isoformat(), ' ',
                        0, '%-7s' % '', 0, '900900', 'FREIGHT  ', 900, '', 0, '', 0, 0,
                        buyer, changed.isoformat(), '08.30.00', 'X'))

    if random.random() < 0.4:
        ot_rows.append((oh_yy, pp, oh_n, '', 'ALL SHIPMENTS MUST REFERENCE THIS PO NUMBER ON THE BOL.',
                        'STD', buyer, created.isoformat(), '', ''))
    return total

idx = 0
for code, stat, meth, count, (lo, hi), _desc in PO_ARCHETYPES:
    for _ in range(count):
        if stat == 'H':
            # Force these over the 25,000 approval limit so the "> max" warning shows
            random.seed(20261005 + idx)
        make_po(code, stat, meth, random.randint(lo, hi), idx)
        idx += 1

OH_COLS = ['OHYY','OH#','OHPP','OHDC','OHSTAT','OHCODE','OHMETH','OHVEND','OHFRT','OHREQ',
           'OHRDTE','OHCHBY','OHCHDT','OHCHTM','OHNN','OHCUID','OHLOC','OHSHIP','OHSATN',
           'OHSADR','OHSCTY','OHSST','OHSZP5','OHSZP4','OHSTCTRY','OHSTPCD','OHORDID',
           'OHEDOC','OHESTS','OHOBACT','OHOBGRP','OHX']
OI_COLS = ['OIYY','OI#','OIPP','OILIN#','OIPART','OIDESC','OISKU','OIUOM','OIQTY','OIRQTY',
           'OIBQTY','OIAKQY','OIAKDT','OIUNIT','OIDDAT','OISTAT','OIREQ','OICSTC','OIGLACT',
           'OIMTLG','OIMTLN','OIPURG','OIWSNN','OIWSJOB','OIWSLOC','OIWSYMD','OIWSTIME',
           'OICHBY','OICHDT','OICHTM','OIX']
ins('ORHDR', OH_COLS, oh_rows)
ins('ORITM', OI_COLS, oi_rows)
ins('ORHTX', ['OHTYY','OHTPP','OHT#','OHTPKEY','OHTXT1','OHTXP','OHTUSE','OHTDAT','OHTCX','OHTDEL'], ot_rows)
ins('ORITX', ['OITYY','OITPP','OIT#','OITLN#','OITPRT','OITSUB'] +
             ['OITXT%d' % i for i in range(1, 9)] + ['OITXTU%d' % i for i in range(1, 9)] +
             ['OITUSE','OITDAT','OITCX'], oit_rows)
ins('ORECOMM', ['ORORDID','ORYY','ORPP','OR#','ORSORDR'], ec_rows)

# ------------------------------------------------------------- WIP jobs/shipments
# A handful of requisitions carry a WIP shipment link so the "WP" button on the
# requisition search screen is enabled for some rows and not others.
for j in range(12):
    nn = '94'
    job = 50010000 + j * 7
    wp_rows.append((nn, job, C.SHIPTOS[j % len(C.SHIPTOS)][1], C.PARTS[j][4], '', 0, '', '',
                    round(random.uniform(5000, 90000), 3), round(random.uniform(0, 5000), 3), '',
                    '', cymd(biz(60 + j)), cymd(biz(20 + j)), cymd(biz(5 + j)),
                    cymd(biz(j)), 83000 + j, 'TMCCUTCH', 1.0, ' ', ''))
    d = biz(5 + j)
    ws_rows.append((nn, job, 'CO', cymd(d), 'CO', 1200 + j,
                    C.SHIPTOS[j % len(C.SHIPTOS)][1], C.PARTS[j][4], '%03d' % (j + 1), 'CO',
                    'CPO-%s-%04d' % (FY, 7100 + j), 1, round(random.uniform(100, 4000), 3),
                    0, 0, 0, 'F', '', cymd(d), 90000 + j, 'TMCCUTCH', ' ', ''))

ins('WIPJOBS', ['WPNN','WPJOB','WPID','WPIT','WPNNOV','WPIDOV','WPITOV','WPJOBP','WPORDQ',
                'WPSHIQ','WPADD','WPRORN','WPENTD','WPOLDD','WPNEWD','WPCYMD','WPCHMS',
                'WPUSER','WPUSEX','WPDEL','WPX'], wp_rows)
ins('WIPSHIP', ['WSNN','WSJOB','WSWH','WSYMD','WSLOC','WSTIME','WSID','WSIT','WSLIN#','WSLOCV',
                'WSPO','WSPCOD','WSQTY','WSPRIQ','WSQ1','WSP1','WSSCH2','WSTO','WSCYMD',
                'WSCHMS','WSUSER','WSDEL','WSX'], ws_rows)

# ------------------------------------------------------------------ requisitions
# Requisition archetypes.  Those with status 'C' are the ones that produced the
# purchase orders above, so the two search screens tell a consistent story.
REQ_ARCHETYPES = [
    (' ', 26, (1, 25),  'approved, waiting to be placed on a PO'),
    ('A', 11, (1, 14),  'audit required'),
    ('E',  7, (1, 10),  'EDI audit'),
    ('R',  9, (2, 30),  'freight rate set'),
    ('D',  5, (10, 90), 'deleted'),
]
om_rows = []
seen = set()

# 1. the requisitions that became PO lines
for (yy, ohn, ln), omreq in sorted(req_for_po.items(), key=lambda x: x[1]):
    oh = next(h for h in oh_rows if h[0] == yy and h[1] == ohn)
    oi = next(i for i in oi_rows if i[0] == yy and i[1] == ohn and i[3] == ln)
    pp, dc, code, vend, buyer = oh[2], oh[3], oh[5], oh[7], oh[9]
    part, desc, qty, uom, unit = oi[4], oi[5], oi[8], oi[7], oi[13]
    created = dt.date.fromisoformat(oh[10]) - dt.timedelta(days=random.randint(1, 9))
    created = workday(created)
    need = workday(dt.date.fromisoformat(oi[14]))
    wip = (j for j in ws_rows)
    use_wip = (omreq % 4 == 0)
    w = ws_rows[omreq % len(ws_rows)] if use_wip else None
    om_rows.append((FY, omreq, pp, dc, 'D' if code == 'D' else code_for(part), 'C',
                    part, desc, qty, uom, round(float(unit), 5), PARTBY[part][1],
                    'CPO-%s-%05d' % (FY, 3000 + omreq),
                    buyer, need.isoformat(), buyer, created.isoformat(), buyer,
                    (int(w[0]) * 100000000 + int(w[1])) if w else 0,
                    w[3] if w else 0, w[4] if w else '', w[5] if w else 0,
                    yy, ohn, pp, '%03d' % ln, qty, uom, buyer,
                    oh[10], oi[14]))
    seen.add(omreq)

# 2. requisitions that have not become POs
nid = max(seen) if seen else 500
for stat, count, (lo, hi), _d in REQ_ARCHETYPES:
    for k in range(count):
        nid += 1
        part = random.choice(CONSUMABLE if stat != 'R' else FREIGHT_P + CONSUMABLE)
        (p, pv, maj, mino, sku, desc, desc2, uom, lead, per, cost, pct) = PARTBY[part]
        created = biz(random.randint(lo, hi))
        need = workday(created + dt.timedelta(days=lead + random.randint(2, 20)))
        dc = random.choice(['CO','CO','CO','CO','VA','SH','WA','HE','SI'])
        pp = PLANT_OF_WH[dc]
        buyer = BUYERS[nid % len(BUYERS)]
        qty = pick_qty(part, random)
        use_wip = (nid % 3 == 0)
        w = ws_rows[nid % len(ws_rows)] if use_wip else None
        om_rows.append((FY, nid, pp, dc, code_for(p), stat,
                        p, desc, qty, uom, round(cost, 5), pv,
                        'CPO-%s-%05d' % (FY, 3000 + nid), buyer, need.isoformat(),
                        buyer, created.isoformat(), '' if stat in ('A', 'E') else buyer,
                        (int(w[0]) * 100000000 + int(w[1])) if w else 0,
                        w[3] if w else 0, w[4] if w else '', w[5] if w else 0,
                        '', 0, '', '', 0, '', '', '0001-01-01', '0001-01-01'))

ins('ORMSR', ['OMYY','OMREQ','OMPP','OMDC','OMCODE','OMSTAT','OMPART','OMDESC','OMQTY','OMUOM',
              'OMEST$','OMVN#','OMCUPO','OMBY','OMRQDT','OMUSER','OMCDAT','OMAPP','OMWO#',
              'OMPOQR','OMWSLC','OMMSD#','OMPOYY','OMPO#','OMPOPP','OMPOIT','OMPOQ','OMPOUM',
              'OMPOBY','OMPODT','OMPODD'], om_rows)

# ---------------------------------------------------- shared saved searches
# PSRUSR blank = a search shared with everyone; the drop-down prefixes it '* '.
ins('PUISRCH', ['PSRAPP','PSRUSR','PSRNAM','PSRDFT','PSRVAL'], [
 ('POSELUI','','Open POs this plant','N',
  '{"SRNN":"94","SRSTAT_":"1","SRSTATH":"0","SRSTATX":"0","SRSTATC":"0"}'),
 ('POSELUI','','On hold - needs approval','N',
  '{"SRNN":"94","SRSTAT_":"0","SRSTATH":"1","SRSTATX":"0","SRSTATC":"0"}'),
 ('POSELUI','','Drop ship orders','N',
  '{"SRNN":"94","SRCODEI":"0","SRCODED":"1","SRCODEE":"0"}'),
 ('PMSELUI','','Requisitions awaiting a PO','N',
  '{"SRNN":"94","SRSTAT_":"1","SRSTATA":"0","SRSTATE":"0","SRSTATC":"0","SRSTATR":"0","SRSTATD":"0"}'),
 ('PMSELUI','','Audit required','N',
  '{"SRNN":"94","SRSTAT_":"0","SRSTATA":"1","SRSTATE":"1","SRSTATC":"0","SRSTATR":"0","SRSTATD":"0"}'),
])

# PODTLUI assigns a new PO number from COADDRES: `CHAIN '94' COAFMT` then
# COAPO# += 1.  Seeding that counter as 0 means the first PO a user creates comes
# out as PR26<1> instead of continuing the sequence - so point it at the highest
# number already issued.
emit("-- next PO number: PODTLUI reads and increments COADDRES.COAPO# for plant '94'")
emit("UPDATE COADDRES SET COAPO# = %d WHERE COAPLT = '94'" % po_no)
emit("UPDATE COADDRES SET COAJOB = %d WHERE COAJOB = 0" % (50010000,))

ins('SAPPOHDCP', ['SPHPO#','SPHSTS','SPHYY','SPHOH#'], [])
ins('XLSLIST', ['XLSUSER','XLSNBR','XLSFILE','XLSSTS'], [])

sys.stdout.write('\n'.join(OUT) + '\n')
sys.stderr.write('PO headers %d, PO lines %d, requisitions %d, vendor parts %d\n'
                 % (len(oh_rows), len(oi_rows), len(om_rows), len(vp_rows)))
