#!/usr/bin/env python3
"""Generate and install the Fletcher EJS shim into the Genie skins.

Why this is needed
------------------
Profound UI renders an EJS screen in `pui.QD` (genie.js). It fetches the
template with a plain XMLHttpRequest and drives `onreadystatechange`:

    function k(t,z){ if(m[t]) z(m[t]); else { var w=new XMLHttpRequest;
      w.open("GET",t,!0); w.onreadystatechange=function(){ 4===w.readyState &&
      (200===w.status ? (m[t]=w.responseText, z(w.responseText))
                      : (console.error("Failed to fetch EJS template: "...), z(null))) };
      w.send(null) } }

That XHR to /profoundui/userdata/ui/... is dropped in this environment, so the
callback receives null and the screen renders blank. Stylesheets are fine -
they load via <link> tags, not XHR.

The shim also restores full-bleed. genie.js escapes the EJS container from the
Genie layout in a helper that first checks for an ancestor carrying one of
Genie's own class names:

    function b(t){ var z=/\b(mainDiv|middleDiv|insideDiv|topDiv)\b/, ...
      if(!w) return null;   // no marker class found -> no escape

On the `pls` skin (the default here) no ancestor carries those classes, so the
escape bails out and the screen renders inside the 5250-sized box - small and
tucked into the top-left corner. We run the same algorithm keyed on our own
wrapper class instead, using the same CSS overrides genie.js applies.

The fix: snapshot each template into the skin's start.html and patch
XMLHttpRequest so those specific URLs resolve from the snapshot instead of the
network. Nothing else is intercepted.

Re-run this after EVERY template edit - a stale snapshot silently serves the
previous version, which is far more confusing than a blank screen.

  tools/gen-fletcher-shim.py [--check]
"""
import base64, os, subprocess, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
UI = os.path.join(ROOT, "htdocs/profoundui/userdata/ui")
SKINS = "/home/drusso/puidist/htdocs/profoundui/userdata/genie skins"
TEMPLATES = ["flfleet/fleet.ejs", "flfleet/machine.ejs",
             "flparts/parts.ejs", "flparts/dupes.ejs",
             "flparts/lookup.ejs",
             "flfleet/custlookup.ejs"]
# Stylesheets are injected as <style> because pui.QD loads them with <link>
# tags whose absolute /profoundui/... path is not resolved through the proxy.
# Safe to inject globally: every Fletcher rule is scoped to a wrapper class.
STYLES = ["fletcher/fletcher-theme.css", "flfleet/fleet.css",
          "flfleet/machine.css", "flparts/parts.css", "flparts/dupes.css",
          "flparts/lookup.css",
          "flfleet/custlookup.css"]
BEGIN = "<!-- BEGIN FLETCHER EJS SHIM (generated by tools/gen-fletcher-shim.py) -->"
END = "<!-- END FLETCHER EJS SHIM -->"


def snapshot():
    out = {}
    for rel in TEMPLATES:
        with open(os.path.join(UI, rel), "rb") as f:
            out[rel] = base64.b64encode(f.read()).decode("ascii")
    return out


def styles():
    css = []
    for rel in STYLES:
        path = os.path.join(UI, rel)
        if os.path.isfile(path):
            css.append(f"/* {rel} */\n" + open(path, encoding="utf-8").read())
    return "\n".join(css)


def build_block(snap, css):
    entries = ",\n".join(f'    "{k}": "{v}"' for k, v in sorted(snap.items()))
    css_b64 = base64.b64encode(css.encode("utf-8")).decode("ascii")
    return f"""{BEGIN}
<script type="text/javascript">
/* Serves EJS templates from an inlined snapshot because the XHR that
   pui.QD uses to fetch them is dropped in this environment. Only the URLs
   listed here are intercepted; every other request goes to the network
   untouched. Regenerate with tools/gen-fletcher-shim.py after any edit. */
(function () {{
  var SNAP = {{
{entries}
  }};

  function decode(b64) {{
    var bin = atob(b64), bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    try {{ return new TextDecoder("utf-8").decode(bytes); }}
    catch (e) {{ return decodeURIComponent(escape(bin)); }}
  }}

  function match(url) {{
    if (!url) return null;
    var u = String(url).split("?")[0].split("#")[0];
    for (var k in SNAP) if (u.indexOf(k) !== -1) return k;
    return null;
  }}

  var open_ = XMLHttpRequest.prototype.open;
  var send_ = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function (method, url) {{
    this.__flKey = (String(method).toUpperCase() === "GET") ? match(url) : null;
    return open_.apply(this, arguments);
  }};

  XMLHttpRequest.prototype.send = function () {{
    var key = this.__flKey, self = this;
    if (!key) return send_.apply(this, arguments);
    var text = decode(SNAP[key]);
    // readyState/status/responseText are read-only getters on the native
    // prototype, so shadow them on this instance before firing the callback.
    setTimeout(function () {{
      try {{
        Object.defineProperty(self, "readyState",   {{ value: 4,    configurable: true }});
        Object.defineProperty(self, "status",       {{ value: 200,  configurable: true }});
        Object.defineProperty(self, "responseText", {{ value: text, configurable: true }});
      }} catch (e) {{ /* older engines: fall through, callback still fires */ }}
      if (typeof self.onreadystatechange === "function") self.onreadystatechange();
      if (typeof self.onload === "function") self.onload();
    }}, 0);
  }};

  /* ---- row selection ----------------------------------------------------
     Double-click a subfile row to select it with the default option. Lives
     here rather than in the RDF's "js" array because script/link fetches to
     userdata/ do not survive the proxy in this environment - the same reason
     the stylesheets are inlined below.

     genie.js collects field values at submit time by scanning named inputs
     and reading .value, so setting the value programmatically is enough - no
     synthetic events needed. Typing the option by hand still works, so the
     screens remain usable with JS disabled. */
  window.flPickRow = function (tr, opt) {{
    if (!tr) return;
    var inp = tr.querySelector("input[name*='.sopt.']");
    if (!inp) return;
    inp.value = opt || "5";
    if (typeof pui !== "undefined" && typeof pui.submit === "function") pui.submit();
  }};

  /* ---- sortable column headings ------------------------------------------
     Click a heading to sort the grid. Type-aware: MM/DD/YYYY dates sort
     chronologically, currency and percentages sort numerically, everything
     else alphabetically. Columns containing inputs (the Opt column) are
     skipped. Re-initialised after every render, guarded by a data flag.

     Note this is where the reference screen's sorting failed - custlist.js
     bound on DOMContentLoaded from the RDF "js" array, which loads before the
     template renders, so it never attached to anything (GJA-891). Running
     from the shim on DOM changes avoids that entirely. */
  function cellKey(td) {{
    var t = (td.textContent || "").replace(/\s+/g, " ").trim();
    if (t === "" || t === "\u2014") return null;
    var m = t.match(/^(\d{{1,2}})\/(\d{{1,2}})\/(\d{{4}})$/);
    if (m) return Number(m[3] + ("0" + m[1]).slice(-2) + ("0" + m[2]).slice(-2));
    /* strip currency, thousands separators, percent - and a leading "+",
       which positive trend values carry and which would otherwise fail the
       numeric test and silently fall through to a string sort */
    var n = t.replace(/[$,%\s]/g, "").replace(/^\+/, "");
    if (n !== "" && /^-?\d*\.?\d+$/.test(n)) return Number(n);
    return t.toLowerCase();
  }}

  function sortBy(table, idx, dir) {{
    var tb = table.tBodies[0];
    if (!tb) return;
    var rows = [].slice.call(tb.rows);
    var keyed = rows.map(function (r, i) {{
      return {{ r: r, i: i, k: r.cells[idx] ? cellKey(r.cells[idx]) : null }};
    }});
    var allNum = keyed.every(function (x) {{
      return x.k === null || typeof x.k === "number";
    }});
    keyed.sort(function (a, b) {{
      if (a.k === null && b.k === null) return a.i - b.i;
      if (a.k === null) return 1;                 /* blanks always last */
      if (b.k === null) return -1;
      var av = allNum ? a.k : String(a.k), bv = allNum ? b.k : String(b.k);
      var c = av < bv ? -1 : av > bv ? 1 : 0;
      return c === 0 ? a.i - b.i : c * dir;       /* stable */
    }});
    keyed.forEach(function (x) {{ tb.appendChild(x.r); }});
  }}

  function initSort() {{
    var tables = document.querySelectorAll(".fl-screen .fl-table");
    for (var t = 0; t < tables.length; t++) {{
      var table = tables[t];
      if (table.getAttribute("data-fl-sort") === "1") continue;
      table.setAttribute("data-fl-sort", "1");
      var head = table.tHead;
      var body = table.tBodies[0];
      if (!head || !head.rows.length || !body || !body.rows.length) continue;
      var ths = head.rows[0].cells;
      for (var i = 0; i < ths.length; i++) {{
        var first = body.rows[0].cells[i];
        if (!first || first.querySelector("input, select, textarea")) continue;
        ths[i].classList.add("fl-sortable");
        ths[i].setAttribute("title", "Click to sort");
        (function (th, idx) {{
          th.addEventListener("click", function () {{
            var dir = th.classList.contains("fl-sort-asc") ? -1 : 1;
            var all = th.parentNode.cells;
            for (var j = 0; j < all.length; j++) {{
              all[j].classList.remove("fl-sort-asc", "fl-sort-desc");
            }}
            th.classList.add(dir === 1 ? "fl-sort-asc" : "fl-sort-desc");
            sortBy(table, idx, dir);
          }});
        }}(ths[i], i));
      }}
    }}
  }}

  /* ---- stylesheets -------------------------------------------------------
     pui.QD loads the RDF's "ejs css" entries with <link> tags pointing at
     /profoundui/userdata/... . Those are not resolved through the proxy, so
     the screen arrives with structure and no styling. Injecting the same CSS
     inline removes the dependency. Every rule is wrapper-scoped, so this is
     safe to apply globally. */
  var CSS_B64 = "{css_b64}";
  (function () {{
    if (document.getElementById("fletcher-ejs-css")) return;
    var st = document.createElement("style");
    st.id = "fletcher-ejs-css";
    st.textContent = decode(CSS_B64);
    document.head.appendChild(st);
  }}());

  /* ---- full-bleed escape -------------------------------------------------
     Mirrors the CSS genie.js applies in its own escape helper, but keyed on
     our wrapper class so it works on any skin, not just those using Genie's
     mainDiv/middleDiv/insideDiv/topDiv markers. */
  var ESC = "fl-esc";
  var css = document.createElement("style");
  css.setAttribute("data-fletcher-escape", "1");
  css.textContent =
    "." + ESC + "{{width:100%!important;max-width:100%!important;min-width:0!important;" +
    "height:auto!important;margin:0!important;padding:0!important;overflow:visible!important;" +
    "box-sizing:border-box!important;text-align:left!important;left:0!important;" +
    "right:auto!important;position:relative!important}}";
  document.head.appendChild(css);

  function escape_() {{
    var prev = document.getElementsByClassName(ESC);
    while (prev.length) prev[0].classList.remove(ESC);
    var el = document.querySelector(".fl-screen");
    if (!el) return;
    var n = el.parentElement;
    while (n && n !== document.body && n !== document.documentElement) {{
      n.classList.add(ESC);
      n = n.parentElement;
    }}
  }}

  /* ---- grid sizing ------------------------------------------------------
     The CSS caps grids with a static calc(), which has to assume how much
     chrome sits above them. Measure it instead: available space is the
     window height minus where the grid actually starts minus the footer.
     Still bounded by the per-screen row cap, so "up to N rows" holds. */
  function sizeGrids() {{
    var grids = document.querySelectorAll(".fl-screen .fl-grid-scroll");
    for (var i = 0; i < grids.length; i++) {{
      var g = grids[i];
      var top = g.getBoundingClientRect().top;
      if (top <= 0) continue;                      /* not laid out yet */
      var screen = g.closest(".fl-screen");
      var foot = screen ? screen.querySelector(".fl-foot") : null;
      var reserve = (foot ? foot.getBoundingClientRect().height : 60) + 40;
      var cap = parseInt(getComputedStyle(screen || g)
                  .getPropertyValue("--fl-grid-max"), 10) || 601;
      var avail = window.innerHeight - top - reserve;
      if (avail > 120) g.style.maxHeight = Math.min(cap, avail) + "px";
    }}
  }}

  var pending = null;
  function schedule() {{
    if (pending) return;
    pending = setTimeout(function () {{ pending = null; escape_(); sizeGrids(); initSort(); }}, 0);
  }}
  if (window.MutationObserver) {{
    new MutationObserver(schedule).observe(document.documentElement,
      {{ childList: true, subtree: true }});
  }}
  schedule();
  window.addEventListener("resize", schedule);

  if (window.console && console.info) {{
    console.info("Fletcher EJS shim active: " + Object.keys(SNAP).length + " template(s)");
  }}
}}());
</script>
{END}"""


def skins():
    r = subprocess.run(["ssh", "dev", f"ls '{SKINS}'"], capture_output=True, text=True)
    names = [n.strip() for n in r.stdout.splitlines() if n.strip() and not n.endswith(".js")]
    return [n for n in names if n]


def install(skin, block, check_only):
    remote = f"{SKINS}/{skin}/start.html"
    r = subprocess.run(["ssh", "dev", f"test -f '{remote}' && cat '{remote}'"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return "no start.html"
    html = r.stdout
    if BEGIN in html and END in html:
        cur = html[html.index(BEGIN):html.index(END) + len(END)]
        if cur == block:
            return "current"
        if check_only:
            return "STALE"
        html = html.replace(cur, block)
    else:
        if check_only:
            return "MISSING"
        if "</body>" not in html:
            return "no </body>"
        html = html.replace("</body>", block + "\n</body>")
    tmp = f"/tmp/gen/start-{skin}.html"
    os.makedirs("/tmp/gen", exist_ok=True)
    open(tmp, "w", encoding="utf-8").write(html)
    if subprocess.run(["scp", "-q", tmp, f"dev:{remote}"]).returncode != 0:
        return "SCP FAILED"
    return "installed"


if __name__ == "__main__":
    check = "--check" in sys.argv
    block = build_block(snapshot(), styles())
    print(f"{'Checking' if check else 'Installing'} shim - {len(TEMPLATES)} templates, "
          f"{len(STYLES)} stylesheets, {len(block)} bytes")
    bad = 0
    for s in skins():
        st = install(s, block, check)
        print(f"  {s:<16} {st}")
        if st in ("STALE", "MISSING", "SCP FAILED"):
            bad += 1
    sys.exit(1 if bad else 0)
