-- Auto-split from hornady_externals.table.sql
CREATE TABLE HDCCMT (
  CXCUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CXCTYP   CHAR(8)       NOT NULL DEFAULT '',
  CXORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  CXSEQ    DECIMAL(5,0)  NOT NULL DEFAULT 0,
  CXCMNT   CHAR(60)      NOT NULL DEFAULT '',
  PRIMARY KEY (CXCUST, CXCTYP, CXORD#, CXSEQ)
) RCDFMT HDRCCMT;
