-- Auto-split from hornady_externals.table.sql
CREATE TABLE HDCUST (
  CUCUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CUNAME   CHAR(30)      NOT NULL DEFAULT '',
  CUADR1   CHAR(30)      NOT NULL DEFAULT '',
  CUADR2   CHAR(30)      NOT NULL DEFAULT '',
  CUCITY   CHAR(20)      NOT NULL DEFAULT '',
  CUSTAT   CHAR(2)       NOT NULL DEFAULT '',
  CUZIP    CHAR(9)       NOT NULL DEFAULT '',
  CUCNTRY  CHAR(3)       NOT NULL DEFAULT '',
  CUPHONE  CHAR(20)      NOT NULL DEFAULT '',
  CUSHPV   CHAR(2)       NOT NULL DEFAULT '',
  CUSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (CUCUST)
) RCDFMT HDRCUST;
