-- Auto-split from hornady_externals.table.sql
CREATE TABLE HDDSHP (
  DSCUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  DSDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  DSNAME   CHAR(30)      NOT NULL DEFAULT '',
  DSADR1   CHAR(30)      NOT NULL DEFAULT '',
  DSCITY   CHAR(20)      NOT NULL DEFAULT '',
  DSSTAT   CHAR(2)       NOT NULL DEFAULT '',
  DSZIP    CHAR(9)       NOT NULL DEFAULT '',
  PRIMARY KEY (DSCUST, DSDSHP)
) RCDFMT HDRDSHP;
