-- HDIMST - Item master
CREATE TABLE HDIMST (
  IMITEM   CHAR(15)      NOT NULL DEFAULT '',
  IMDESC   CHAR(30)      NOT NULL DEFAULT '',
  IMUOM    CHAR(3)       NOT NULL DEFAULT '',
  IMWGT    DECIMAL(9,3)  NOT NULL DEFAULT 0,
  IMIMWG   DECIMAL(9,3)  NOT NULL DEFAULT 0,
  IMSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (IMITEM)
) RCDFMT HDRIMST;
