-- HDIWHS - Item warehouse
CREATE TABLE HDIWHS (
  IWITEM   CHAR(15)      NOT NULL DEFAULT '',
  IWWHS    DECIMAL(3,0)  NOT NULL DEFAULT 0,
  IWQOH    DECIMAL(11,2) NOT NULL DEFAULT 0,
  IWFTCL   CHAR(6)       NOT NULL DEFAULT '',
  IWSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (IWITEM, IWWHS)
) RCDFMT HDRIWHS;
