-- HDPCLS - Pallet class master (PC* prefix per HYR0138)
CREATE TABLE HDPCLS (
  PCPCLS   CHAR(4)       NOT NULL DEFAULT '',
  PCPCDS   CHAR(30)      NOT NULL DEFAULT '',
  PCSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (PCPCLS)
) RCDFMT HDRPCLS;
