-- HREMPL - HR Employee master (EM* prefix per HYR0600 lookups).
CREATE TABLE HREMPL (
  EMEMPL   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  EMFNAM   CHAR(18)      NOT NULL DEFAULT '',
  EMLNAM   CHAR(18)      NOT NULL DEFAULT '',
  EMDEPT   CHAR(6)       NOT NULL DEFAULT '',
  EMSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (EMEMPL)
) RCDFMT HREMPLR;
