-- HYPIDTA - In-transit detail (IS* prefix per HYR0600 refs)
CREATE TABLE HYPIDTA (
  ISORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  ISTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  ISORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  ISBLN#   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  ISITEM   CHAR(15)      NOT NULL DEFAULT '',
  ISQTY    DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (ISORD#, ISTURN, ISORL#, ISBLN#)
) RCDFMT HYRIDTA;
