-- HYPINTR - Shipment in-transit (keys per kf_ORD#/kf_TURN/kf_AIV# sizes in HYR0600)
CREATE TABLE HYPINTR (
  GIORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  GITURN   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  GIAIV#   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  GIGRP#   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  GISTS    CHAR(1)       NOT NULL DEFAULT '',
  GIUSER   CHAR(10)      NOT NULL DEFAULT '',
  GIWSID   CHAR(10)      NOT NULL DEFAULT '',
  GITSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (GIORD#, GITURN, GIAIV#)
) RCDFMT HYRINTR;
