-- HYPMILG - Hornady message log
CREATE TABLE HYPMILG (
  MLTSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  MLLGTY   CHAR(8)       NOT NULL DEFAULT '',
  MLPGM    CHAR(10)      NOT NULL DEFAULT '',
  MLUSER   CHAR(10)      NOT NULL DEFAULT '',
  MLWS     CHAR(10)      NOT NULL DEFAULT '',
  MLMSG    CHAR(132)     NOT NULL DEFAULT '',
  MLDATA   CHAR(512)     NOT NULL DEFAULT ''
) RCDFMT HYRMILG;
