-- HYPMPCD - Master pack code (MD* prefix per HYLMPCD3 keys)
CREATE TABLE HYPMPCD (
  MDORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  MDTURN   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  MDSRL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  MDMP     CHAR(2)       NOT NULL DEFAULT '',
  MDDESC   CHAR(30)      NOT NULL DEFAULT '',
  PRIMARY KEY (MDORD#, MDTURN, MDSRL#)
) RCDFMT HYRMPCD;
