-- HYPPMLG - Pallet message log (output file in HYR0138)
CREATE TABLE HYPPMLG (
  PLTSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PLPGM    CHAR(10)      NOT NULL DEFAULT '',
  PLUSER   CHAR(10)      NOT NULL DEFAULT '',
  PLMSG    CHAR(132)     NOT NULL DEFAULT ''
) RCDFMT HYRPMLG;
