-- HYPPCLS - Pallet contents
CREATE TABLE HYPPCLS (
  CSSRL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  CSORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  CSTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  CSBOL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  CSSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (CSSRL#)
) RCDFMT HYRPCLS;
