-- HYPPLLT - Shipping pallet master (PM* fields per HYR0138)
CREATE TABLE HYPPLLT (
  PMSHTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  PMPSRL#  DECIMAL(8,0)  NOT NULL DEFAULT 0,
  PMDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  PMSHT    CHAR(1)       NOT NULL DEFAULT '',
  PMBOL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  PMINVC   CHAR(1)       NOT NULL DEFAULT '',
  PMEMPL   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  PMEMTY   CHAR(1)       NOT NULL DEFAULT '',
  PMLEMPL  DECIMAL(5,0)  NOT NULL DEFAULT 0,
  PMLEMTY  CHAR(1)       NOT NULL DEFAULT '',
  PMLACT   CHAR(8)       NOT NULL DEFAULT '',
  PMHZLB   CHAR(1)       NOT NULL DEFAULT '',
  PMSRC    CHAR(1)       NOT NULL DEFAULT '',
  PMLEN    DECIMAL(7,2)  NOT NULL DEFAULT 0,
  PMWID    DECIMAL(7,2)  NOT NULL DEFAULT 0,
  PMHGT    DECIMAL(7,2)  NOT NULL DEFAULT 0,
  PMTSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PMLSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PMOSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (PMSHTO, PMPSRL#)
) RCDFMT HYRPLLT;
