-- HYPRCLT - Recall lot
CREATE TABLE HYPRCLT (
  RLITEM   CHAR(15)      NOT NULL DEFAULT '',
  RLLOT    CHAR(10)      NOT NULL DEFAULT '',
  RLSTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (RLITEM, RLLOT)
) RCDFMT HYRRCLT;
