-- HYPSTRK - Shipment tracking (6-col schema per INSERT in HYR0600)
CREATE TABLE HYPSTRK (
  TKORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  TKTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  TKSEQ    DECIMAL(3,0)  NOT NULL DEFAULT 0,
  TKTRK#   CHAR(30)      NOT NULL DEFAULT '',
  TKUSER   CHAR(10)      NOT NULL DEFAULT '',
  TKTSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (TKORD#, TKTURN, TKSEQ, TKTRK#)
) RCDFMT HYRSTRK;
