-- HYPSSCC - SSCC content master (with SCPSRL# pallet serial)
CREATE TABLE HYPSSCC (
  SCSRL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  SCORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  SCORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  SCBLN#   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  SCLOT#   CHAR(10)      NOT NULL DEFAULT '',
  SCSSCC  DECIMAL(20,0) NOT NULL DEFAULT 0,      
  SCPSRL#  DECIMAL(8,0)  NOT NULL DEFAULT 0,
  SCSTS    CHAR(1)       NOT NULL DEFAULT '',
  S1SRL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  S1ORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  S1ORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  S1BLN#   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  S1LOT#   CHAR(10)      NOT NULL DEFAULT '',
  PRIMARY KEY (SCSRL#, SCORD#, SCORL#, SCBLN#, SCLOT#)
) RCDFMT HYRSSCC;
