-- HYPSCWK - SSCC work file (with S1PSRL# pallet serial)
CREATE TABLE HYPSCWK (
  S1SRL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  S1ORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  S1ORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  S1BLN#   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  S1LOT#   CHAR(10)      NOT NULL DEFAULT '',
  S1SSCC  DECIMAL(20,0) NOT NULL DEFAULT 0,      
  S1ITEM   CHAR(15)      NOT NULL DEFAULT '',
  S1QSTC   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  S1TURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  S1PSRL#  DECIMAL(8,0)  NOT NULL DEFAULT 0,
  PRIMARY KEY (S1SRL#, S1ORD#, S1ORL#, S1BLN#, S1LOT#)
) RCDFMT HYRSCWK;
