-- HYPSGTC - Shipment tote control
CREATE TABLE HYPSGTC (
  TCGRP#   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  TCTOTE   CHAR(20)      NOT NULL DEFAULT '',
  TCTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  TCTSEQ   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  TCBLTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  TCSHTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  TCDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  TCSTS    CHAR(1)       NOT NULL DEFAULT '',
  TCTSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (TCGRP#, TCTOTE, TCTURN, TCTSEQ)
) RCDFMT HYRSGTC;
