-- HYPSGCV - Shipment customer-via (added CV* metadata columns)
CREATE TABLE HYPSGCV (
  CVGRP#   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  CVBLTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CVSHTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CVDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CVSHPV   CHAR(2)       NOT NULL DEFAULT '',
  CVSVDS   CHAR(30)      NOT NULL DEFAULT '',
  CVVWTY   CHAR(1)       NOT NULL DEFAULT '',
  CVEMPL   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  CVUSER   CHAR(10)      NOT NULL DEFAULT '',
  CVWS     CHAR(10)      NOT NULL DEFAULT '',
  CVTSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  CVTSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (CVGRP#, CVBLTO, CVSHTO, CVDSHP, CVSHPV)
) RCDFMT HYRSGCV;
