-- HYPSGTS - Shipment tote scan
CREATE TABLE HYPSGTS (
  TSGRP#   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  TSTOTE   CHAR(20)      NOT NULL DEFAULT '',
  TSTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  TSTSEQ   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  TSRSEQ   DECIMAL(5,0)  NOT NULL DEFAULT 0,
  TSQSCN   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  TSTSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  TSUSER   CHAR(10)      NOT NULL DEFAULT '',
  PRIMARY KEY (TSGRP#, TSTOTE, TSTURN, TSTSEQ, TSRSEQ)
) RCDFMT HYRSGTS;
