-- Auto-split from hornady_externals.table.sql
CREATE TABLE HYPTDTA (
  TDORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  TDTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  TDTRK#   CHAR(30)      NOT NULL DEFAULT '',
  TDSHPV   CHAR(2)       NOT NULL DEFAULT '',
  TDTSTP1  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (TDORD#, TDTURN)
) RCDFMT HYRTDTA;
