-- HYPWSOQ - Work order quantity (minimal skeleton)
CREATE TABLE HYPWSOQ (
  WSORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  WSTURN   DECIMAL(9,0)  NOT NULL DEFAULT 0,
  WSITEM   CHAR(15)      NOT NULL DEFAULT '',
  WSQTY    DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (WSORD#, WSTURN, WSITEM)
) RCDFMT HYRWSOQ;
