-- Auto-split from hornady_externals.table.sql
CREATE TABLE HYW0610A (
  WAOEORD  DECIMAL(8,0)  NOT NULL DEFAULT 0,
  WATURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  WAQPIK   DECIMAL(11,2) NOT NULL DEFAULT 0,
  WASTS    CHAR(1)       NOT NULL DEFAULT '',
  PRIMARY KEY (WAOEORD, WATURN)
) RCDFMT HYRW0610A;
