-- OEBOLH - Bill of lading header (minimal skeleton)
CREATE TABLE OEBOLH (
  OBBOL#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  OBCUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OBSHTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OBDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OBSHPV   CHAR(2)       NOT NULL DEFAULT '',
  OBSTS    CHAR(1)       NOT NULL DEFAULT '',
  OBTSTP   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (OBBOL#)
) RCDFMT OEBOLHR;
