-- Auto-split from hornady_externals.table.sql
CREATE TABLE OEDTWK (
  O1OCTL   CHAR(8)       NOT NULL DEFAULT '',
  O1ORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  O1ITEM   CHAR(15)      NOT NULL DEFAULT '',
  O1QTY    DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (O1OCTL, O1ORL#)
) RCDFMT OEDTWKR;
