-- OEHDWK - Order header work
CREATE TABLE OEHDWK (
  H1OCTL   CHAR(8)       NOT NULL DEFAULT '',
  H1ORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  H1TURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  H1CUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  H1UDF3   CHAR(50)      NOT NULL DEFAULT '',
  PRIMARY KEY (H1OCTL)
) RCDFMT OEHDWKR;
