-- OEOCMT - Order comments
CREATE TABLE OEOCMT (
  OCORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  OCTURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  OCORL#   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  OCDOCT   CHAR(8)       NOT NULL DEFAULT '',
  OCSEQ    DECIMAL(5,0)  NOT NULL DEFAULT 0,
  OCCTYP   CHAR(8)       NOT NULL DEFAULT '',
  OCCMNT   CHAR(60)      NOT NULL DEFAULT '',
  PRIMARY KEY (OCORD#, OCTURN, OCORL#, OCSEQ)
) RCDFMT OEOCMTR;
