-- OEORHD uses 'OE' field prefix per HYR0600 references.
CREATE TABLE OEORHD (
  OEORD#   DECIMAL(8,0)  NOT NULL DEFAULT 0,
  OETURN   DECIMAL(4,0)  NOT NULL DEFAULT 0,
  OECUST   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OEBLTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OESHTO   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OEDSHP   DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OESHPV   CHAR(2)       NOT NULL DEFAULT '',
  OEPO#    CHAR(25)      NOT NULL DEFAULT '',
  OESTS    CHAR(1)       NOT NULL DEFAULT '',
  OECTRM   CHAR(2)       NOT NULL DEFAULT '',
  OEODT    DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OERDT    DECIMAL(7,0)  NOT NULL DEFAULT 0,
  OEBUSY   CHAR(1)       NOT NULL DEFAULT '',
  OEUDF9   CHAR(50)      NOT NULL DEFAULT '',
  OEUCA1   CHAR(2)       NOT NULL DEFAULT '',
  OEORRF   CHAR(20)      NOT NULL DEFAULT '',
  PRIMARY KEY (OEORD#, OETURN)
) RCDFMT OEORHDR;
