-- PICKBATDP - Pick Batch Detail
-- Source: Hornady/src/HornadyDemo/Source/PICKBATDP.PF (Glenn Hopwood, Sept 2021)
-- 1:1 promotion of the DDS PF.  REFFLDs resolve to:
--   ORD#  -> DECIMAL(8,0)
--   SEQ3  -> DECIMAL(3,0)
--   TURN  -> DECIMAL(4,0)
--   ORL#  -> DECIMAL(4,0)
--   ITEM  -> CHAR(15)
--   IMQT  -> DECIMAL(11,2)
-- Primary key is the DDS UNIQUE+K combination: PICKBAT,PICKSEQ.
CREATE TABLE PICKBATDP (
  PICKBAT     DECIMAL(8,0)  NOT NULL DEFAULT 0,
  PICKSEQ     DECIMAL(3,0)  NOT NULL DEFAULT 0,
  PICKOVRORD  DECIMAL(4,0)  NOT NULL DEFAULT 0,
  PICKTURN    DECIMAL(4,0)  NOT NULL DEFAULT 0,
  PICKORD     DECIMAL(8,0)  NOT NULL DEFAULT 0,
  PICKORDL    DECIMAL(4,0)  NOT NULL DEFAULT 0,
  PICKITEM    CHAR(15)      NOT NULL DEFAULT '',
  PICKITEMUM  CHAR(5)       NOT NULL DEFAULT '',
  PICKITEMCT  CHAR(50)      NOT NULL DEFAULT '',
  PICKWHS     DECIMAL(3,0)  NOT NULL DEFAULT 0,
  PICKSTKRM   CHAR(3)       NOT NULL DEFAULT '',
  PICKAISLE   CHAR(4)       NOT NULL DEFAULT '',
  PICKLOC     CHAR(8)       NOT NULL DEFAULT '',
  PICKITMST   CHAR(1)       NOT NULL DEFAULT '',
  PICKNEED    DECIMAL(11,2) NOT NULL DEFAULT 0,
  PICKQTYP    DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (PICKBAT, PICKSEQ)
) RCDFMT PICKBATDR;
