-- PICKBATHP - Pick Batch Header
-- Source: Hornady/src/HornadyDemo/Source/PICKBATHP.PF (Glenn Hopwood, Sept 2021)
-- Schema is a 1:1 promotion of the DDS PF to SQL.  REFFLD(ORD#) resolves to
-- DECIMAL(8,0) via src/fldref.pf.  PICKBAT is the primary key (UNIQUE in DDS).
CREATE TABLE PICKBATHP (
  PICKBAT     DECIMAL(8,0) NOT NULL DEFAULT 0,
  PICKSEQNO   DECIMAL(8,0) NOT NULL DEFAULT 0,
  PICKER      CHAR(10)     NOT NULL DEFAULT '',
  PICKINVLOC  CHAR(4)      NOT NULL DEFAULT '',
  PICKSTAT    CHAR(1)      NOT NULL DEFAULT '',
  PICKNUMITM  DECIMAL(5,0) NOT NULL DEFAULT 0,
  PICKNUMPCS  DECIMAL(5,0) NOT NULL DEFAULT 0,
  PICKSTART   TIMESTAMP    NOT NULL DEFAULT '0001-01-01-00.00.00.000000',
  PICKEND     TIMESTAMP    NOT NULL DEFAULT '0001-01-01-00.00.00.000000',
  PICKDUR     DECIMAL(6,0) NOT NULL DEFAULT 0,
  PICKCRTUSR  CHAR(10)     NOT NULL DEFAULT '',
  PICKCRTTZ   TIMESTAMP    NOT NULL DEFAULT '0001-01-01-00.00.00.000000',
  PICKCHGUSR  CHAR(10)     NOT NULL DEFAULT '',
  PICKCHGTZ   TIMESTAMP    NOT NULL DEFAULT '0001-01-01-00.00.00.000000',
  PICKCHGJBU  CHAR(10)     NOT NULL DEFAULT '',
  PICKCHGJBN  CHAR(10)     NOT NULL DEFAULT '',
  PICKCHGJB#  DECIMAL(6,0) NOT NULL DEFAULT 0,
  PICKTOT     CHAR(50)     NOT NULL DEFAULT '',
  PRIMARY KEY (PICKBAT)
) RCDFMT PICKBATHR;
