     D* This will need to be updated anytime criteria is added for a search
     DdsSrchCrit       ds                  inz
     D dsAgtCrit                    100    inz
     D  dsAgtGrp                      3  0 overlay(dsAgtCrit:1)
     D  dsAgtName                    40    overlay(dsAgtCrit:*next)
     D  dsAgt#                        5  0 overlay(dsAgtCrit:*next)
     D  dsAgtProdN                   40    overlay(dsAgtCrit:*next)
     D  dsAgtProd#                    5  0 overlay(dsAgtCrit:*next)
     D  dsAgtStat                     1    overlay(dsAgtCrit:*next)
     D  dsAgtGrpSt                    1    overlay(dsAgtCrit:*next)
     D dsClmCrit                    171    inz
     D  dsClmGrp                      3  0 overlay(dsClmCrit:1)
     D  dsClmYr                       3  0 overlay(dsClmCrit:*next)
     D  dsClmCase                     7  0 overlay(dsClmCrit:*next)
     D  dsClmSS#                      9    overlay(dsClmCrit:*next)
     D  dsClmAccDt                    8  0 overlay(dsClmCrit:*next)
     D  dsClmLName                   30    overlay(dsClmCrit:*next)
     D  dsClmFName                   15    overlay(dsClmCrit:*next)
     D  dsClmEmp#                     9  0 overlay(dsClmCrit:*next)
     D  dsClmDiv                      5    overlay(dsClmCrit:*next)
     D  dsClmLoc                     10    overlay(dsClmCrit:*next)
     D  dsClmEmpNm                   40    overlay(dsClmCrit:*next)
     D  dsClmStat                     1    overlay(dsClmCrit:*next)
     D  dsClmUser                     3    overlay(dsClmCrit:*next)
     D  dsClmLtFl                     1    overlay(dsClmCrit:*next)
     D  dsClmJrSt                     2    overlay(dsClmCrit:*next)
     D  dsClmSCL#                    25    overlay(dsClmCrit:*next)
     D dsEmpCrit                    256    inz
     D  dsEmpName                    40    overlay(dsEmpCrit:1)
     D  dsEmpGrp                      3  0 overlay(dsEmpCrit:*next)
     D  dsEmpEmp#                     9  0 overlay(dsEmpCrit:*next)
     D  dsEmpDiv                      5    overlay(dsEmpCrit:*next)
     D  dsEmpAgt#                     5  0 overlay(dsEmpCrit:*next)
     D  dsEmpAgtNm                   40    overlay(dsEmpCrit:*next)
     D  dsEmpCarr                    25    overlay(dsEmpCrit:*next)
     D  dsEmpFein                     9  0 overlay(dsEmpCrit:*next)
     D  dsEmpSt#                     20    overlay(dsEmpCrit:*next)
     D  dsEmpAddr                    40    overlay(dsEmpCrit:*next)
     D  dsEmpFQ                       1    overlay(dsEmpCrit:*next)
     D  dsEmpNB                       1    overlay(dsEmpCrit:*next)
     D  dsEmpFrDt                     8  0 overlay(dsEmpCrit:*next)
     D  dsEmpToDt                     8  0 overlay(dsEmpCrit:*next)
     D  dsEmpQteTp                    1    overlay(dsEmpCrit:*next)
     D  dsRateSt                      2    overlay(dsEmpCrit:*next)
     D  dsEmpUnder                    3    overlay(dsEmpCrit:*next)
     D  dsEmpQteSt                    1    overlay(dsEmpCrit:*next)
     D  dsCustId                     20    overlay(dsEmpCrit:*next)
     D  dsEmpLink                    15    overlay(dsEmpCrit:*next)
     D dsFiller                       1  0
      *
